open-mmlab/mmpretrain

README.md
Remove bibtex and contact to encourage more contributors to join in.
=> Remove bibtex and contact

mmcls/datasets/utils.py
[urlretrieve](https://docs.python.org/3/library/urllib.request.html#urllib.request.urlretrieve) might be deprecated in the future
=> Replace urlretrieve with urlopen in dataset.utils

configs/_base_/schedules/imagenet_bs2048_coslr.py, configs/_base_/schedules/imagenet_bs256_coslr.py
Fix the parameter in policy in 'configs/base/schedules/*_coslr.py', which is changed from 'policy='CosineAnealing' to policy='CosineAnnealing'. The inference can be find in https://github.com/open-mmlab/mmcv/blob/17e4732c49a5d58d236a3006df0130d166001c18/mmcv/runner/hooks/lr_updater.py#L228.
=> Fix the parameter in cosine lr schedule

docs/getting_started.md, docs/tutorials/finetune.md, docs/tutorials/new_modules.md, mmcls/datasets/cifar.py, mmcls/datasets/pipelines/transforms.py, requirements.txt, requirements/optional.txt, tests/test_pipelines/test_transform.py
This P.R. adds support to use [albumentations ](https://albumentations.ai/docs/ ) transforms; following schema used in [mmdet](https://github.com/open-mmlab/mmdetection/tree/master/mmdet)
=> Add albumentations

docs/getting_started.md
Added step for downloading meta data for ImageNet.
=> Update ImageNet data setup in getting_started document

tools/pytorch2onnx.py
It can be merged after PR https://github.com/open-mmlab/mmclassification/pull/16 is merged, as it requires the added `simple_test` function.
=> Add pytorch2onnx

mmcls/utils/collect_env.py
@ycxioooong Could you please review this? Thanks.
=> Change to use mmcv.utils.collect_env to avoid duplicate codes

mmcls/datasets/samplers/distributed_sampler.py
@ycxioooong Could you please review this?
=> Fix bug in distributed_sampler

mmcls/models/losses/eval_metrics.py, tests/test_dataset.py
=> fix bug in recall and precision

tools/train.py
@ycxioooong Could you please review this?
=> Fix bug in gpu_ids in distributed training

.github/workflows/build.yml, mmcls/apis/test.py
When data is severely insufficient, empty part_results on certain gpus could make the overall outputs empty therefore be an issue.
=> [Bug] Fix bug in collect_results

mmcls/models/losses/eval_metrics.py, tests/test_dataset.py
=> [Bug] Fix bug in eval_metrics

mmcls/models/losses/__init__.py, mmcls/models/losses/focal_loss.py, tests/test_losses.py
Hey,
In this pull request, python version of focal loss was adopted from mmdet. 
Note that the cuda version in mmcv seems only support the single label case therefore is not adopted. 
Please kindly take a look. Thanks.
=> [Feature] Add focal loss for multilabel task

docs/stat.py, mmcls/models/losses/__init__.py, mmcls/models/losses/cross_entropy_loss.py, tests/test_losses.py
Hi,
In this pull request, bce loss was implemented.
Please kindly take a look. Thanks.
=> [Feature] Add bce loss for multilabel task

configs/lenet/README.md, configs/mobilenet_v2/README.md, configs/resnet/README.md, configs/resnext/README.md, configs/seresnet/README.md, configs/seresnext/README.md, configs/shufflenet_v1/README.md, configs/shufflenet_v2/README.md, configs/vgg/README.md, docs/stat.py
=> [Docs] Add tags in README.md

mmcls/models/losses/__init__.py, mmcls/models/losses/asymmetric_loss.py, tests/test_losses.py
Hey,
In this pull request, asl in paper 'Asymmetric Loss For Multi-Label Classification' was implemented. Please refer to https://arxiv.org/abs/2009.14119.
Note that the default value of gamma follows the suggestions in the paper rather than in the code they provide.
Please kindly have a look. Thanks.
=> [Feature] Add asymmetric loss for multilabel task

mmcls/core/evaluation/eval_hooks.py, mmcls/datasets/pipelines/transforms.py, mmcls/models/backbones/mobilenet_v2.py, mmcls/models/backbones/mobilenet_v3.py, mmcls/models/backbones/regnet.py, mmcls/models/backbones/resnest.py, mmcls/models/backbones/resnet.py, mmcls/models/backbones/resnext.py, mmcls/models/backbones/seresnext.py, mmcls/models/backbones/shufflenet_v1.py, mmcls/models/backbones/shufflenet_v2.py, mmcls/models/backbones/vgg.py, mmcls/models/losses/accuracy.py, mmcls/models/losses/asymmetric_loss.py, mmcls/models/losses/cross_entropy_loss.py, mmcls/models/losses/focal_loss.py, mmcls/models/utils/make_divisible.py
Hi,
It has come to my knowledge that 'optional' should only be used when indicating None is an acceptable type. So this pull request fixes the optional issue in docstring. 
Pls refer to the following link on the issue.
https://stackoverflow.com/questions/34846731/where-can-i-find-more-information-about-new-syntax-supported-in-google-style-doc
Thx.
=> [Fix] Fix optional issues in docstring

configs/lenet/README.md, configs/mobilenet_v2/README.md, configs/resnet/README.md, configs/resnext/README.md, configs/seresnet/README.md, configs/seresnext/README.md, configs/shufflenet_v1/README.md, configs/shufflenet_v2/README.md, configs/vgg/README.md, docs/stat.py
=> Update stat to classify papers

mmcls/models/backbones/vgg.py
Hi,
This pull request fix a bug in vgg init_weights. Pls take a look. 
Thx.
=> [Bug] Fix bug in vgg weight_init

configs/resnet/resnet50_b32x8_label_smooth_imagenet.py, configs/resnet/resnet50_b64x32_warmup_label_smooth_imagenet.py
Hi,
This pull request fixes #105. Please take a look.Thx.
=> [Bug] Fix typo in configs

mmcls/core/evaluation/__init__.py, mmcls/core/evaluation/eval_metrics.py, mmcls/datasets/base_dataset.py, mmcls/models/losses/accuracy.py, tests/test_dataset.py
Hi,
This pull request add a argument thr in accuracy, precision, recall and f1 score to support evaluation under certain threshold conditions. 
Please take a look. Thank you.
=> [Feature] Add thrs in eval_metrics

mmcls/datasets/pipelines/transforms.py, tests/test_pipelines/test_transform.py
Hi Xiongyu,
This pull request fixes #60. 
Pls kindly take a look.
Thank you.
=> [Fix] Fix RandomCrop and RandomResizedCrop

mmcls/datasets/pipelines/formating.py
Hi, 
This pull request fixes #59. 
Simply removing meta_keys in __repr__ shall solve the issue safely since this is used in no configs.
Thx.
=> [Bug] Fix bug in Collect

tools/test.py
Hi Xiongyu,
In this pull request, tiny changes are made in test.py since now we have more metrics than just accuracy.
=> [Fix] Fix test.py

README.md, docs/changelog.md, mmcls/version.py
Hi Xiongyu,
Docs are updated in this pull request.
Thank you.
=>  Bump version to 0.8.0 

configs/_base_/models/resnet50_cifar_mixup.py, configs/_base_/models/resnet50_mixup.py, configs/resnet/resnet50_b16x8_cifar10_mixup.py, configs/resnet/resnet50_b32x8_mixup_imagenet.py, mmcls/models/classifiers/image.py, mmcls/models/losses/cross_entropy_loss.py, mmcls/models/utils/__init__.py, mmcls/models/utils/mixup.py, tests/test_backbones/test_utils.py, tests/test_classifiers.py, tests/test_losses.py
Hi~
This pr aims to add "mixup" trick mentioned in "Bag of Tricks for Image Classification with Convolutional Neural Networks". So far, the "mixup" operation has only one version which is the same as the official implementation.
=> [Feature] Add "mixup" from Bag of Tricks

mmcls/datasets/pipelines/__init__.py, mmcls/datasets/pipelines/auto_augment.py, tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, Translate pipeline is added. 
This pull request has conflicts with #163, I will resolve them after #163 is merged.
=> [Feature] Add translate pipeline

mmcls/datasets/pipelines/__init__.py, mmcls/datasets/pipelines/auto_augment.py, tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, Rotate pipeline is added. 
=> [Feature] Add rotate pipeline

mmcls/datasets/pipelines/__init__.py, mmcls/datasets/pipelines/auto_augment.py, tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, ColorTransform pipeline is added. 
=> [Feature] Add color pipeline

mmcls/models/classifiers/image.py, tools/pytorch2onnx.py
This pr focus on support onnx dynamic shape export.
=> support dynamic shape export to onnx

configs/fp16/README.md, configs/fp16/resnet50_b32x8_fp16_dynamic_imagenet.py, configs/fp16/resnet50_b32x8_fp16_imagenet.py, mmcls/apis/train.py, mmcls/models/classifiers/base.py, tools/test.py
Hi,
In this pull request, FP16 is supported and 2 configs are provided.
Benchmark will be provided in a separate pull request.
=> [Feature] Support fp16 training

configs/fp16/README.md
Hi,
Resnet50 trained using fp16 is uploaded to model zoo and related doc is updated. Pls kindly take a look. Thank you.
=> [Doc] Add model zoo doc for fp16

.github/workflows/build.yml
Hi,
In this pull request, ci is fixed otherwise mmcv can not be successfully installed.
Thanks.
=> [Fix] Update pip install mmcv command in ci

README.md, docs/changelog.md, docs/install.md, mmcls/version.py, requirements/readthedocs.txt
Hi Xiongyu,
Docs are updated for version 0.10.0 in this pull request.
#187 is omitted since it should not be of users' concerns.
=> Bump version to 0.10.0

docs/index.rst, docs/tutorials/onnx2tensorrt.md, docs/tutorials/pytorch2onnx.md
This PR add  pytorch2onnx.py's and onnx2tensorrt.py's user-guide document.
=> Add pytorch to onnx and onnx to tensorrt doc

docs/tutorials/pytorch2onnx.md, tools/pytorch2onnx.py
This PR focus on add the simplify option in pytorch2onnx.py, which can simplify the model, and update relevant document in pytorch2onnx.md
=> Add simplify option in pytorch2onnx.py and Update doc

mmcls/datasets/pipelines/__init__.py, mmcls/datasets/pipelines/auto_augment.py, tests/test_pipelines/test_auto_augment.py
Hi, 
In this pull request, random augmentation is support and 2 more transforms are supported for RandAug.
Pls kindly take a look. Thanks.
=> [Feature] Support random augmentation

mmcls/models/heads/cls_head.py, tests/test_heads.py
Hi,
This minor pr add cal_acc(bool) to ClsHead in cls_head.py. Because if you use Mixup / CutMix or something like that during training, it is not reasonable to calculate accuracy.
Pls kindly take a look.
Thank you.
=> [Feature]Add cal_acc to cls_head.py 

mmcls/apis/inference.py, tools/test.py
- check for CLASSES in checkpoint meta when key meta does not exists
=> [Fix] check for CLASSES in checkpoint meta

.github/workflows/build.yml, README.md, mmcls/__init__.py, mmcls/models/utils/cutmix.py
Hi,
This pull request fixes 3 things:
1. Add pt1.7 and pt1.8 to CI. After the CI passes, I will further verify the compatibility by training. And I will let you know when it's done.
2. Add missing "Projects in OpenMMLab" section to `README.md`.
3. Update `__init__.py` to ensure MMCV compatibility.
=> [Fix] Fix version

configs/_base_/models/vit_base_patch32_384_finetune.py, configs/_base_/models/vit_large_patch16_224_finetune.py, configs/_base_/models/vit_large_patch16_384_finetune.py, configs/_base_/models/vit_large_patch32_384_finetune.py, configs/vision_transformer/vit_base_patch32_384_finetune_imagenet.py, configs/vision_transformer/vit_large_patch16_224_finetune_imagenet.py, configs/vision_transformer/vit_large_patch16_384_finetune_imagenet.py, configs/vision_transformer/vit_large_patch32_384_finetune_imagenet.py, mmcls/models/backbones/vision_transformer.py
Hi,
This minor pr add some vit configs, including vit_base_patch32_384_finetune_imagenet.py, etc.
Pls kindly take a look.
Thank you.
=> Add some vit configs

configs/_base_/models/resnet50_cifar_cutmix.py, configs/_base_/models/resnet50_cutmix.py
Hi,
This minor pr add cutmix_prob to configs.
Pls kindly take a look.
Thank you.
=> [Bug]add cutmix_prob to config

.pre-commit-config.yaml, mmcls/apis/train.py, tools/train.py
In this modification `tools/train.py` supports `--device cpu` argument.
=> Support training on CPU

docs/tutorials/pytorch2onnx.md
This PR add table format of pytorch2onnx of online doc: https://mmclassification.readthedocs.io/
=> [Doc]: add table format of pytorch2onnx

README.md, README_zh-CN.md, docs/changelog.md, docs/install.md, docs_zh-CN/install.md, mmcls/version.py
Hi,
Docs are updated for version 0.11.0 in this pull request.
=> Bump version to v0.11.0

docs/tutorials/new_dataset.md, docs_zh-CN/tutorials/finetune.md, docs_zh-CN/tutorials/new_dataset.md
Original new_dataset.md has an error about how to create a new dataset class. I fixed it and add two Chinese translations of two tutorials.
=> [Docs] Fix error in new_dataset.md and add Chinese translation of finture.md, new_dataset.md

mmcls/models/heads/base_head.py
=> [Fix]: Fix wrong word.

configs/_base_/datasets/cifar100_bs16.py, configs/_base_/datasets/cifar10_bs16.py
Hi, 
The configs for Cifar are updated. I will check the model zoo to see if ckpts need to be updated.
=> [Bug] Update cifar config

docs/index.rst, docs/switch_language.md, docs/tutorials/onnx2tensorrt.md, docs/tutorials/pytorch2onnx.md, docs_zh-CN/Makefile, docs_zh-CN/conf.py, docs_zh-CN/index.rst, docs_zh-CN/stat.py, docs_zh-CN/switch_language.md, docs_zh-CN/tutorials/onnx2tensorrt.md, docs_zh-CN/tutorials/pytorch2onnx.md
I have finished the Chinese docs sphinx setting, and you can preview it here.
https://mmcls-test.readthedocs.io/zh_CN/latest/index.html
PS: switch language button is not available on the preview site because it redirects to `mmclassification.readthedocs.io`
=> Build chinese translation in readthedocs

docker/serve/Dockerfile, docker/serve/config.properties, docker/serve/entrypoint.sh, docs/tutorials/model_serving.md, setup.cfg, tools/deployment/mmcls2torchserve.py, tools/deployment/mmcls_handler.py
This P.R. enables serving MMClassification models with TorchServe. A new section Model Serving has been added to tutorials.
=> Add mmcls2torchserve

docs/tutorials/onnx2tensorrt.md, docs/tutorials/pytorch2onnx.md, mmcls/core/export/__init__.py, mmcls/core/export/test.py, tools/deployment/onnx2tensorrt.py, tools/deployment/test.py
This PR adds TensorRT test tools.
=> [Feature] TensorRT test tools.

mmcls/apis/train.py, tools/test.py
1. remove MMDataParallel when using cpu
2. add support for cpu testing 
fix #277
=> Fix bug for CPU training

mmcls/models/backbones/mobilenet_v2.py, mmcls/models/backbones/resnet.py, mmcls/models/backbones/shufflenet_v1.py, mmcls/models/backbones/shufflenet_v2.py
1. Fix bug in shufflenet.When using init_cfg("pretrain", "xxx"),the loaded weight will be overwritten.
2.refactor the init_weights in mobilenetv2
=> [Fix] Fix init_weights bug in some backbones and update Readme

MANIFEST.in
Hi. This minor pr fixes the MANIFEST.in by changing model_zoo.yml to model-index.yml. Pls take a look.
=> [Fix]Fix MANIFEST.in

.gitignore, MANIFEST.in, README.md, README_zh-CN.md, setup.py
1. Add mim related files to `.gitignore`
2. Generate mim related files when installing
3. Add mim introduction in docs
Refers to https://github.com/open-mmlab/mmpose/pull/706
=> [Feature] Support mim

docs/conf.py, mmcls/datasets/pipelines/auto_augment.py, mmcls/datasets/pipelines/transforms.py
1. Add escape symbols for underscores in formulas.
2. Support Chinese characters in pdf output.
=> [Docs] Fix some bugs in readthedocs pdf build.

mmcls/models/utils/se_layer.py, tests/test_models/test_utils/test_se.py
Add Enhance SE-layer to support both [Regnet](https://github.com/Ezra-Yu/mmclassification/blob/regnet/mmcls/models/utils/se_layer.py), [Efficientnet](https://github.com/LXXXXR/mmclassification/blob/efficientnet_test/mmcls/models/utils/se_layer.py) and [RepVGG](https://github.com/bofen97/RepVGG-openMMLab/blob/main/backbones/RepVGG.py#L14).
add squeeze_channels and divisor
mmcls/models/utils/se_layer.py
no.
.
**Before PR**:
**After PR**:
=> [enhance] Add enhenced SE

configs/resnest/README.md, configs/seresnet/metafile.yml, configs/tnt/README.md, configs/vision_transformer/README.md, model-index.yml
Add algorithm readme for `resnest`, `tnt`, and `vit`. And update `model-index.yml`
**Before PR**:
**After PR**:
=> [Docs] Add algorithm readme and update meta yml

.github/workflows/build.yml, setup.py
Refers to https://github.com/open-mmlab/mmcv/pull/1291 and https://github.com/open-mmlab/mmcv/pull/1141
As the title.
No
**Before PR**:
**After PR**:
=> [CI] Add PyTorch 1.9 and Python 3.9 build workflow, and remove some CI.

requirements/docs.txt
As recommended by [readthedocs](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies), we should fix the version of sphinx. Refers to https://github.com/open-mmlab/mmcv/pull/1301
As the title.
**Before PR**:
**After PR**:
=> [Docs] Fix the version of sphinx

tools/convert_models/publish_model.py
1.  add datetime in outfilename.
2.  saving ckpt using version<1.6 torch format
3.  auto mkdir of outfile
1.  add datetime in outfilename.
2.  saving ckpt using version<1.6 torch format
3.  auto mkdir of outfile
no
**Before PR**:
**After PR**:
=> [Enchence] Add datetime info and saving model using <torch1.6 fromat

mmcls/datasets/pipelines/transforms.py
Fix transforms.py docstring 
Fix transforms.py docstring 
No
**Before PR**:
**After PR**:
=> fix transforms.py docstring

requirements/runtime.txt
PR #402 used `packaging` in `mmcls/__init__.py` but did not add it into the requirements file. This led to the failure of CI for downstream projects.
requirements/runtime.txt
None
**Before PR**:
**After PR**:
=> [Fix]: Fix runtime requirements.

README.md, README_zh-CN.md, configs/fp16/metafile.yml, docs/_static/css/readthedocs.css, docs/community/CONTRIBUTING.md, docs/conf.py, docs/getting_started.md, docs/index.rst, docs/install.md, docs/tutorials/finetune.md, docs_zh-CN/_static/css/readthedocs.css, docs_zh-CN/community/CONTRIBUTING.md, docs_zh-CN/conf.py, docs_zh-CN/getting_started.md, docs_zh-CN/index.rst, docs_zh-CN/install.md, docs_zh-CN/model_zoo.md, docs_zh-CN/tutorials/finetune.md
There are some problems with our docs. Here I revised the `getting_started.md` and `install.md` and almost rewrote the `finetune.md`.
1. As the title.
2. Add `model_zoo.md` and `CONTRIBUTING.md` to our docs.
3. Disable the auto-wrap of code blocks. It may cause some code ugly.
No
No
**Before PR**:
**After PR**:
=> [Docs] Update `getting_started.md` and `install.md` and rewrite `finetune.md`

docs/conf.py, docs/index.rst, docs/tutorials/config.md, docs_zh-CN/conf.py, docs_zh-CN/index.rst
Use docs link of other projects and add MMCV docs.
-  docs/conf.py
-  docs_zh-CN/conf.py 
And fixed the misused `documents`, it should be `documentation`
**Before PR**:
**After PR**:
=> [Docs] Use docs link of other projects and add MMCV docs.

configs/_base_/models/mlp_mixer_base_patch16.py, configs/_base_/models/mlp_mixer_base_patch32.py, configs/mlp_mixer/mlp_mixer-base_p16_64xb64_in1k.py, configs/mlp_mixer/mlp_mixer-base_p32_64xb64_in1k.py, mmcls/models/backbones/__init__.py, mmcls/models/backbones/mlp_mixer.py, tests/test_models/test_backbones/test_mlp_mixer.py
Add MLP-Mixer Image Classifier
- Add MLP-Mixer backbone
- Add MLP-Mixer config files
**Before PR**:
**After PR**:
=> [Feature] Add MLP Mixer Backbone.

mmcls/models/losses/focal_loss.py, tests/test_metrics/test_losses.py
The implemented version of focal loss did not support single label tasks. This PR allows focal loss to work with both single label and multi label tasks. Closes #533 
Modified focal loss implementation to enable single label tasks and added test for the single label case.
**Before PR**:
**After PR**:
=> [Enhance] Focal loss for single label tasks

.circleci/config.yml, .pre-commit-config.yaml
We will turn to CircleCI to replace GitHub Actions. Refers to https://github.com/open-mmlab/mmocr/pull/611
1. Add the CircleCI config file and the GitHub workflow will be reserved during the trial.
2. Use the official markdownlint tool to fit the environment of CircleCI.
No
No
**Before PR**:
**After PR**:
=> [CI] Use CircleCI to do unit tests.

README.md, README_zh-CN.md, docs/conf.py, docs/tutorials/runtime.md, docs_zh-CN/conf.py, mmcls/datasets/imagenet21k.py, mmcls/models/backbones/t2t_vit.py, mmcls/models/backbones/vision_transformer.py, requirements/docs.txt, setup.cfg
The dependency of our docs `m2r` is outdated, and it's not used. Now remove it and fix some other errors.
**Before PR**:
**After PR**:
=> [Docs] Fix docs build dependency.

.github/workflows/build.yml, .github/workflows/lint.yml
Refers to https://github.com/open-mmlab/mmcv/pull/1537
As the title
**Before PR**:
**After PR**:
=> [CI] Cancel previous runs that are not completed.

tools/analysis_tools/analyze_logs.py
https://github.com/open-mmlab/mmclassification/issues/661
If this PR introduces a new feature, it is better to list some …
=> [Fix] Fix bug which breaks `cal_train_time` in `analyze_logs.py`.

tools/visualizations/vis_cam.py
=> [Fix] Fix API changes in  `pytorch-grad-cam>=1.3.7`

mmcls/models/utils/augment/cutmix.py, mmcls/models/utils/augment/identity.py, mmcls/models/utils/augment/mixup.py, mmcls/models/utils/augment/utils.py, tests/test_models/test_utils/test_augment.py
Make mixup compatible with multi label.
**Before PR**:
**After PR**:
=> [Enhance] Suport Mixup&Cutmix for multi-label task.

README.md, README_zh-CN.md
Update the `README.md` according to the OpenMMLab standard.
As the title.
**Before PR**:
**After PR**:
=> [Docs] Update README.md

docs/zh_CN/tools/analysis.md
示例脚本应执行“eval_metric.py”，而不是analyze_results.py。
另外应该是利用 `tools/test.py` 的 `--out` 参数，而不是`tools/train.py`
If this PR …
=> [Docs] Fix typo in `analysis.md`

docs/en/tools/analysis.md
=> Fix bug of analysis.md

.pre-commit-config.yaml, tools/convert_models/efficientnet_to_mmcls.py, tools/convert_models/mlpmixer_to_mmcls.py, tools/convert_models/reparameterize_repvgg.py, tools/convert_models/repvgg_to_mmcls.py, tools/deployment/test_torchserver.py, tools/visualizations/vis_lr.py, tools/visualizations/vis_pipeline.py
=> [Enhance] Add a new pre-commit-hook to automatically add a copyright.

README.md, README_zh-CN.md
Add MMRotate.
As the title.
**Before PR**:
**After PR**:
=> [Docs] Add MMRotate in README.

tools/convert_models/mlpmixer_to_mmcls.py, tools/convert_models/reparameterize_repvgg.py, tools/convert_models/repvgg_to_mmcls.py, tools/deployment/test.py
As title refer to #693 
as title.
**Before PR**:
**After PR**:
=> [Enhance] Return code 1 if scripts runs failed.

mmcls/models/utils/augment/__init__.py, mmcls/models/utils/augment/resizemix.py, tests/test_models/test_utils/test_augment.py
Support resizemix.
[paper](https://arxiv.org/pdf/2012.11101.pdf)
**Before PR**:
**After PR**:
=> [Feature] Support resizemix

tools/convert_models/vgg_to_mmcls.py, tools/kfold-cross-valid.py, tools/test.py, tools/train.py
=> [Enhance] Use `--a-b` instead of `--a_b` in arguments.

README.md, README_zh-CN.md, docker/serve/Dockerfile, docs/en/changelog.md, docs/en/install.md, docs/zh_CN/install.md, mmcls/version.py
The benchmark regression is almost done.
Please check the release information.
=> Bump to v0.22.0

README.md, README_zh-CN.md
=> wrong model link 

MANIFEST.in, setup.py
Add mim to extras_require in setup.py
As the title. And update `MANIFEST.in`
**Before PR**:
**After PR**:
=> [Fix] Add mim to extras_require in setup.py

tools/train.py
Add some options in `train.py`:
**To resume training:**
```shell
python tools/train.py configs/resnet/resnet18_8xb32_in1k.py --resume
python tools/train.py configs/resnet/resnet18_8xb32_in1k.py --resume checkpoints/resnet18_8xb32_in1k.pth
```
**AMP training**
```shell
python tools/train.py configs/resnet/resnet18_8xb32_in1k.py --amp
```
**Enable auto-scaling learning rate**
```shell
python tools/train.py configs/resnet/resnet18_8xb32_in1k.py --auto-scale-lr
```
=> [Improve] Add `--amp`, `--resume` and `--auto-scale-lr` options in `tools/train.py`.

configs/regnet/regnetx-400mf_8xb128_in1k.py, configs/resnet/resnet50_8xb32-coslr-preciseBN_in1k.py, mmcls/engine/hooks/precise_bn_hook.py, tests/test_engine/test_hooks/test_precise_bn_hook.py
=> [Refactor] Refactor  Precise BN Hook

configs/mobilenet_v3/mobilenet-v3-small_8xb16_cifar10.py, mmcls/models/backbones/repvgg.py, mmcls/models/classifiers/image.py, tests/test_models/test_classifiers.py, tools/analysis_tools/get_flops.py
fix issue https://github.com/open-mmlab/mmclassification/issues/979
fix a typo in repvgg.py: branch_nrom to branch_norm
=> [Improve] Fixed typo in `RepVGG`.

demo/image_demo.py, docker/Dockerfile, docker/serve/Dockerfile, docs/en/get_started.md, docs/zh_CN/get_started.md
1. Refactor get started docs
2. The demo script is broken and I fixed it.
3. Update the docker file about the installation of mmcv&mmengine.
=> [Docs] Refactor get started docs and fix the demo and docker file.

docs/en/user_guides/finetune.md, docs/zh_CN/user_guides/finetune.md
refine fine-tune docs
**Before PR**:
**After PR**:
=> [Docs] refactor fine-tune tutorial

docs/en/_static/css/readthedocs.css, docs/en/api/apis.rst, docs/en/api/data_process.rst, docs/en/api/datasets.rst, docs/en/api/engine.rst, docs/en/api/evaluation.rst, docs/en/api/models.rst, docs/en/api/structures.rst, docs/en/api/utils.rst, docs/en/api/visualization.rst, docs/zh_CN/_static/css/readthedocs.css, mmcls/datasets/multi_label.py, mmcls/datasets/transforms/__init__.py, mmcls/datasets/transforms/formatting.py, mmcls/datasets/transforms/processing.py
Refactor API
**Before PR**:
**After PR**:
=> [Docs] Refactor API docs.

docs/en/user_guides/analysis.md
=> [Doc] update analysis

docs/en/advanced_guides/modules.md, docs/en/conf.py, docs/zh_CN/advanced_guides/modules.md, docs/zh_CN/conf.py
refactor new module docs
**Before PR**:
**After PR**:
=> [Docs] refactor new modules tutorial

docs/en/_static/css/readthedocs.css, docs/en/api/data_process.rst, docs/en/api/engine.rst, docs/en/conf.py, docs/en/migration.md, docs/zh_CN/_static/css/readthedocs.css, docs/zh_CN/conf.py, mmcls/models/classifiers/image.py, mmcls/models/utils/data_preprocessor.py, mmcls/structures/cls_data_sample.py, requirements/docs.txt, tests/test_models/test_utils/test_data_preprocessor.py
**This is a PR for MMCLS 1.x**
1. Add migration documentation.
2. Fix the wrong `train_cfg` argument.
=> [Docs] Add Migration documentation.

CONTRIBUTING.md
=> [Doc] update contributing

docs/en/user_guides/inference.md, docs/zh_CN/user_guides/inference.md
Add Inference Doc
**Before PR**:
**After PR**:
=> [Docs] Add Inference Doc

docs/en/user_guides/train_test.md, docs/zh_CN/user_guides/train_test.md
Add training and test documentation.
=> [Docs] Add training and test docs.

docs/en/getting_started.md, docs/zh_CN/getting_started.md
Fix the wrong reference name in tutorial of both languages (En & Zh)
Change the reference link to correct one (the one existing in the site), not the ancient one: …
=> [Doc] Fix typo for wrong reference

mmcls/models/backbones/vision_transformer.py
=> [Feature]: Add ViT-H

README.md, README_zh-CN.md, configs/_base_/models/mvit/mvitv2-base.py, configs/_base_/models/mvit/mvitv2-large.py, configs/_base_/models/mvit/mvitv2-small.py, configs/_base_/models/mvit/mvitv2-tiny.py, configs/_base_/schedules/imagenet_bs1024_adamw_swin.py, configs/_base_/schedules/imagenet_bs2048_AdamW.py, configs/mvit/README.md, configs/mvit/metafile.yml, configs/mvit/mvitv2-base_8xb256_in1k.py, configs/mvit/mvitv2-large_8xb256_in1k.py, configs/mvit/mvitv2-small_8xb256_in1k.py, configs/mvit/mvitv2-tiny_8xb256_in1k.py, docs/en/api/models.rst, mmcls/models/backbones/__init__.py, mmcls/models/backbones/mvit.py, model-index.yml, tests/test_models/test_backbones/test_mvit.py
=> [Feature] Support MViT for MMCLS 1.x

mmcls/models/losses/label_smooth_loss.py
Add loss_weight to LabelSmoothLoss. Pls take a look.
=> [Fix]Add loss_weight to LabelSmoothLoss

docs/en/migration.md
Typo in migration document (gard -> grad)
**Before PR**:
**After PR**:
=> Fix typo in migration document

tools/misc/verify_dataset.py
make the `tools/misc/verify_dataset.py` tool available.
```shell
tools/misc/verify_dataset.py configs/regnet/regnetx-400mf_8xb128_in1k.py  --num-process 10 --phase test
```
**Before PR**:
**After PR**:
=> [Fix] Fix verify-dataset tool in 1.x

docs/en/tools/analysis.md, docs/zh_CN/tools/analysis.md
=> [Docs] Fixed typo for `--out-dir` option of analyze_results.py

docs/en/tutorials/config.md
=> Fix typo in config.md

docs/en/advanced_guides/schedule.md, docs/zh_CN/advanced_guides/schedule.md
update schedule documents
**Before PR**:
**After PR**:
=> [Docs] add 1x docs schedule

README.md, README_zh-CN.md, mmcls/apis/inference.py
=> Add MMYOLO projects link in MMCLS1.x

docs/en/_static/css/readthedocs.css, docs/en/conf.py, docs/en/device/npu.md, docs/en/index.rst, docs/zh_CN/_static/css/readthedocs.css, docs/zh_CN/conf.py, docs/zh_CN/device/npu.md, docs/zh_CN/index.rst
Add NPU result
docs/en/device/npu.md
None
None
**Before PR**:
**After PR**:
=> [Docs] Add NPU support page.

README.md, README_zh-CN.md
=> Add MMEval projects link in README

configs/_base_/models/swin_transformer_v2/base_256.py, configs/_base_/models/swin_transformer_v2/small_256.py, configs/_base_/models/swin_transformer_v2/tiny_256.py, configs/swin_transformer/README.md, configs/swin_transformer_v2/README.md, docs/en/conf.py, docs/en/stat.py, docs/zh_CN/conf.py, docs/zh_CN/stat.py, mmcls/apis/inference.py, requirements/docs.txt
Improve Swin Doc
1. Add Tabs enxtation
2. folded the abstract
3. improve the readme of swin and swinv2.
```
**Predict image**  # tab1
Content1  without "**xxxx**"
**Use the model**    # tab2
Content2  without "**xxxx**"
**Command**          # tab3
Content3 without "**xxxx**"
```
**Before PR**:
**After PR**:
=> [Enhance] Improve Swin Doc and Add Tabs enxtation

configs/mobilevit/README.md, configs/vision_transformer/README.md
As titled
**Before PR**:
**After PR**:
=> [Docs] Improve ViT and MobileViT model pages

.dev_scripts/benchmark_regression/1-benchmark_valid.py, README.md, README_zh-CN.md, configs/_base_/models/hornet/hornet-base-gf.py, configs/_base_/models/hornet/hornet-base.py, configs/_base_/models/hornet/hornet-large-gf.py, configs/_base_/models/hornet/hornet-large-gf384.py, configs/_base_/models/hornet/hornet-large.py, configs/_base_/models/hornet/hornet-small-gf.py, configs/_base_/models/hornet/hornet-small.py, configs/_base_/models/hornet/hornet-tiny-gf.py, configs/_base_/models/hornet/hornet-tiny.py, configs/hornet/README.md, configs/hornet/hornet-base-gf_8xb64_in1k.py, configs/hornet/hornet-base_8xb64_in1k.py, configs/hornet/hornet-small-gf_8xb64_in1k.py, configs/hornet/hornet-small_8xb64_in1k.py, configs/hornet/hornet-tiny-gf_8xb128_in1k.py, configs/hornet/hornet-tiny_8xb128_in1k.py, configs/hornet/metafile.yml, docs/en/api/models.rst, mmcls/models/backbones/__init__.py, mmcls/models/backbones/hornet.py, model-index.yml, tests/test_models/test_backbones/test_hornet.py, tools/model_converters/hornet2mmcls.py
Related PR: https://github.com/open-mmlab/mmclassification/pull/1013
**Before PR**:
**After PR**:
=> [Feature] Support HorNet Backbone for dev1.x

mmcls/models/backbones/repvgg.py, tests/test_models/test_backbones/test_repvgg.py
Related PR: https://github.com/open-mmlab/mmclassification/pull/1025
**Before PR**:
**After PR**:
=> [Enhancement] RepVGG for YOLOX-PAI for dev-1.x

configs/convnext/README.md
=> [Doc] update the readme of convnext

tools/deployment/mmcls2torchserve.py
Changed mmcv to mmengine
Updated for 1.x
**Before PR**:
Used github.dev web-based editor to make quick change, hopefully didn't break any linting rules
**After PR**:
=> [Fix] Update mmcls2torchserve.

configs/_base_/datasets/imagenet_bs64_deit3_224.py, configs/_base_/datasets/imagenet_bs64_deit3_384.py, configs/_base_/datasets/imagenet_bs64_edgenext_256.py, configs/_base_/datasets/imagenet_bs64_swin_256.py, configs/_base_/models/deit3/deit3-base-p16-224.py, configs/_base_/models/deit3/deit3-base-p16-384.py, configs/_base_/models/deit3/deit3-huge-p14-224.py, configs/_base_/models/deit3/deit3-large-p16-224.py, configs/_base_/models/deit3/deit3-large-p16-384.py, configs/_base_/models/deit3/deit3-medium-p16-224.py, configs/_base_/models/deit3/deit3-small-p16-224.py, configs/_base_/models/deit3/deit3-small-p16-384.py, configs/_base_/models/mvit/mvitv2-base.py, configs/_base_/models/mvit/mvitv2-large.py, configs/_base_/models/mvit/mvitv2-small.py, configs/_base_/models/mvit/mvitv2-tiny.py
With the refactor of `batch_aguments`, there are still a few of configs not being adapted.
see changes for details.
**Before PR**:
**After PR**:
=> [Fix ] fix configs due to api refactor of num_classes

mmcls/models/backbones/convnext.py, tests/test_models/test_backbones/test_convnext.py
Related to https://github.com/open-mmlab/mmclassification/pull/1152
Support Activation Checkpointing for ConvNeXt
Followed the code pattern of SwinTransformer.
=> [Feature] Support Activation Checkpointing for ConvNeXt

docs/en/conf.py, docs/zh_CN/conf.py, requirements/docs.txt
Add a version switch button in the banner and add a deprecated warning on the master docs.
=> [Docs] Add version banner and version warning in master docs.

mmcls/models/backbones/beit.py
=> [Fix] Fix dict update

configs/mobilenet_v2/README.md, configs/mobilenet_v3/README.md
=> [Docs] Update MobileNetv2 & MobileNetv3 readme

mmcls/core/hook/wandblogger_hook.py
=> [Fix] Fix a bug caused MMClsWandbHook stuck

.owners.yml
=> [Bot] Update assignee schedule.

.circleci/test.yml
=> [CI] Update CI to test PyTorch 1.13.0.

.circleci/config.yml, .github/workflows/build.yml, .owners.yml, mmcls/models/heads/multi_label_head.py, mmcls/models/heads/multi_label_linear_head.py
Close #1250.
The sigmoid calculation is sensitive to precision, which will change the top-k result from multi-label heads.
As the title.
**Before PR**:
**After PR**:
=> [Fix] Force the sigmoid calculation in multi-label head to be full-precision.

tools/visualizations/vis_cam.py
The original CAM visualization tool is broken by the modification of the data preprocessor.
Fix the problem.
**Before PR**:
**After PR**:
=> [Fix] Fix CAM visualization.

configs/repvgg/repvgg-A0_deploy_in1k.py
Fix RepVGG-deploy Error Config
**Before PR**:
**After PR**:
=> [Fix] Fix RepVGG-deploy Error Config

docs/zh_CN/useful_tools/complexity_analysis.md, docs/zh_CN/useful_tools/log_result_analysis.md, docs/zh_CN/useful_tools/print_config.md, docs/zh_CN/useful_tools/verify_dataset.md
=> [Docs] Translate some tools tutorials to Chinese (Codecamp).

mmcls/models/backbones/res2net.py, mmcls/models/backbones/resnet.py
update resnet according to timm
code link: https://github.com/rwightman/pytorch-image-models/blob/main/timm/models/resnet.py#L600
If this PR introduces a new feature, it is better to …
=> [Enhance] Add stochastic depth decay rule in resnet

configs/cae/cae_vit-base-p16_8xb256-amp-coslr-300e_in1k.py, configs/simmim/simmim_swin-base-w6_16xb128-amp-coslr-800e_in1k-192px.py, configs/simmim/simmim_swin-base-w6_8xb256-amp-coslr-100e_in1k-192px.py, configs/simmim/simmim_swin-large-w12_16xb128-amp-coslr-800e_in1k-192px.py, mmpretrain/datasets/transforms/processing.py
=> [Fix] Fix value error while start training

mmpretrain/visualization/visualizer.py, tools/visualization/browse_dataset.py
BEiT
SimMIM
BYOL
ConvNeXt (keep unchanged)
**Before PR**:
**After PR**:
=> [Refactor] Refactor browse_dataset to support selfsup pipeline

projects/fgia_accv2022_1st/README.md, projects/fgia_accv2022_1st/config/mae_vit-large-p16_8xb512-amp-coslr-1600e_in1k.py, projects/maskfeat_video/README.md, projects/maskfeat_video/configs/maskfeat_mvit-small_16xb32-amp-coslr-300e_k400.py, projects/maskfeat_video/configs/maskfeat_mvit-small_8xb32-amp-coslr-300e_k400.py, projects/maskfeat_video/configs/mvit-small_ft-8xb16-coslr-100e_k400.py, projects/maskfeat_video/models/__init__.py, projects/maskfeat_video/models/hog_generator_3d.py, projects/maskfeat_video/models/maskfeat.py, projects/maskfeat_video/models/maskfeat_mvit.py, projects/maskfeat_video/models/transforms.py, projects/maskfeat_video/tools/dist_train.sh, projects/maskfeat_video/tools/slurm_train.sh, projects/maskfeat_video/tools/train.py
=> [Refactor] Add projects from mmselfsup

configs/byol/byol_resnet50_16xb256-coslr-200e_in1k.py, configs/densecl/densecl_resnet50_8xb32-coslr-200e_in1k.py, configs/mocov2/mocov2_resnet50_8xb32-coslr-200e_in1k.py, configs/mocov3/mocov3_resnet50_8xb512-amp-coslr-100e_in1k.py, configs/mocov3/mocov3_resnet50_8xb512-amp-coslr-300e_in1k.py, configs/mocov3/mocov3_resnet50_8xb512-amp-coslr-800e_in1k.py
Set `zero_init_residual=False` in some contrastive learning algorithms …
=> [Fix] Fix init bug of r50 in contrastive learning

README.md, README_zh-CN.md
Update Readme, point to pretrain branch
**Before PR**:
**After PR**:
=> [DOC] Update Readme

configs/maskfeat/maskfeat_vit-base-p16_8xb256-amp-coslr-300e_in1k.py
=> [Fix] Fix config of maskfeat

README.md, README_zh-CN.md
Update recommended branch from MMClassification to MMPreTrain in README
**Before PR**:
**After PR**:
=> [DOC] Update recommended branch from MMClassification to MMPreTrain in README

mmcls/evaluation/metrics/single_label.py
Fix test acc time consumption increase in multi-GPUs
**Before PR**:
**After PR**:
=> [Fix] Fix test acc time consumption increase in multi-GPUs

mmcls/engine/hooks/precise_bn_hook.py, tests/test_engine/test_hooks/test_precise_bn_hook.py
Fix Precise BN Hook bug refer to https://github.com/open-mmlab/mmclassification/issues/1384
from 
```
batch_inputs, data_samples = model.data_preprocessor(data, False)
model(batch_inputs, data_samples)
```
To
```
data = model.data_preprocessor(data, False)
model(**data)
```
**Before PR**:
**After PR**:
=> [Bug] Fix Precise BN Hook bug

.circleci/test.yml, .github/workflows/deploy.yml, .github/workflows/lint.yml, .github/workflows/pr_stage_test.yml, .github/workflows/publish-to-pypi.yml, .github/workflows/test_mim.yml, mmpretrain/__init__.py, tests/test_tools.py
ref: https://github.com/open-mmlab/mmengine/pull/1026
- Test PyTorch 2.0 in CI and Fix unit tests.
- Update docker image to ubuntu-22.04 due to https://github.com/actions/runner-images/issues/6002
- Update the action application with latest [tutorial](https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python)
**Before PR**:
**After PR**:
=> [Fix] Update CI

mmpretrain/models/backbones/vision_transformer.py
=> [Refactor] Add LayerNorm to ViT avg_featmap output

README.md, README_zh-CN.md
=> [Docs] Fix docs link

mmpretrain/engine/hooks/precise_bn_hook.py, tests/test_engine/test_hooks/test_precise_bn_hook.py
refer to #1386 in dev-1.x branch
**Before PR**:
**After PR**:
=> [Fix] Fix Precise-BN-Hook bug

docs/zh_CN/user_guides/config.md
train cfg: Removed old description
**Before PR**:
**After PR**:
=> train cfg: Removed old description

mmpretrain/models/backbones/vit_sam.py
=> [Refactor] Support to freeze channel reduction and add layer decay function

.github/workflows/pr_stage_test.yml, .github/workflows/test_mim.yml, mmpretrain/models/heads/multi_label_cls_head.py
Fix the bug in binary cross entropy loss when using multi-label datasets e.g.VOC2007
The issue from #1495 .
Fix CI according to some experiments, From ```mim install -e .```   -->  ```mim install .```
**Before PR**:
**After PR**:
=> [Fix] Fix the bug in binary cross entropy loss

configs/poolformer/README.md
Update PoolFormer citation to CVPR version
=> [DOC] Update PoolFormer citation to CVPR version

README.md, README_zh-CN.md, docs/en/user_guides/dataset_prepare.md
Update MMagic link
fix 404 error in #1516 
**Before PR**:
**After PR**:
=> [DOC] Update MMagic link

mmpretrain/models/selfsup/milan.py
It has a bug while initializing the model.
**Before PR**:
**After PR**:
=> [Fix] Fix clip generator init bug

configs/beit/beit_beit-base-p16_8xb256-amp-coslr-300e_in1k.py, configs/beitv2/beitv2_beit-base-p16_8xb256-amp-coslr-1600e_in1k.py, configs/beitv2/beitv2_beit-base-p16_8xb256-amp-coslr-300e_in1k.py
Related issue: #1527 
**Before PR**:
**After PR**:
=> [Fix] Fix config of beit

mmpretrain/models/selfsup/beit.py, mmpretrain/models/selfsup/cae.py, mmpretrain/models/selfsup/mae.py, mmpretrain/models/selfsup/maskfeat.py, tests/test_models/test_selfsup/test_beit.py, tests/test_models/test_selfsup/test_cae.py, tests/test_models/test_selfsup/test_mae.py, tests/test_models/test_selfsup/test_maskfeat.py, tests/test_models/test_selfsup/test_milan.py
=> [Fix] Fix ddp bugs

mmpretrain/datasets/gqa_dataset.py, mmpretrain/datasets/scienceqa.py, mmpretrain/evaluation/metrics/__init__.py, mmpretrain/evaluation/metrics/scienceqa.py, tests/test_evaluation/test_metrics/test_scienceqa.py
=> [Feature]: Add ScienceQA Metrics

projects/example_project/README.md
Fix README in the example_project.
**Before PR**:
**After PR**:
=> [Fix] Fix README in the example_project

mmpretrain/datasets/scienceqa.py, mmpretrain/evaluation/metrics/scienceqa.py, tests/test_evaluation/test_metrics/test_scienceqa.py
=> [Fix]: Fix scienceqa

README.md, README_zh-CN.md, docker/serve/Dockerfile, docs/en/get_started.md, docs/en/notes/changelog.md, docs/en/notes/faq.md, docs/zh_CN/get_started.md, docs/zh_CN/notes/faq.md, mmpretrain/__init__.py, mmpretrain/version.py
=> Bump version to v1.0.0rc8

mmpretrain/datasets/scienceqa.py
=> [Feature]: Add image_only param

docs/en/advanced_guides/pipeline.md, docs/zh_CN/advanced_guides/pipeline.md
According to the tutorial, an error will result in a circular import
`mmpretrain.datasets` should be changed to `mmpretrain.registry`
**Before PR**:
**After PR**:
=> [Doc] Fixed circular import error for new TRANSFORMS

configs/_base_/datasets/coco_caption.py, configs/_base_/datasets/coco_retrieval.py
=> [Feat] Add download link for coco caption and retrieval annotations.

mmpretrain/models/backbones/vit_sam.py
=> [Fix] fix sam bug

configs/_base_/datasets/vsr.py, mmpretrain/datasets/__init__.py, mmpretrain/datasets/vsr.py
Add support for vsr dataset.
**Before PR**:
**After PR**:
=> [Feature] Add support for vsr dataset

configs/_base_/datasets/vizwiz.py, mmpretrain/datasets/__init__.py, mmpretrain/datasets/vizwiz.py
Add support for VizWiz dataset.
**Before PR**:
**After PR**:
=> [Feature] Add support for VizWiz dataset.

README.md, README_zh-CN.md, configs/otter/README.md, configs/otter/metafile.yml, configs/otter/otter-9b_caption.py, configs/otter/otter-9b_vqa.py, docs/en/api/models.rst, mmpretrain/models/multimodal/__init__.py, mmpretrain/models/multimodal/flamingo/adapter.py, mmpretrain/models/multimodal/otter/__init__.py, mmpretrain/models/multimodal/otter/otter.py, model-index.yml, tools/model_converters/otter2mmpre.py
Support multi-modality algorithm Otter.
=> [Feature] Support otter

README.md, README_zh-CN.md, configs/llava/README.md, configs/llava/llava-7b-v1_caption.py, configs/llava/metafile.yml, docs/en/api/models.rst, mmpretrain/models/multimodal/__init__.py, mmpretrain/models/multimodal/llava/__init__.py, mmpretrain/models/multimodal/llava/llava.py, mmpretrain/models/multimodal/llava/modules.py, model-index.yml, tools/model_converters/llava-delta2mmpre.py
Support LLavA multimodal algorithm
=> [Feature] Support LLaVA

mmpretrain/apis/feature_extractor.py, mmpretrain/apis/image_caption.py, mmpretrain/apis/image_classification.py, mmpretrain/apis/image_retrieval.py, mmpretrain/apis/visual_grounding.py, mmpretrain/apis/visual_question_answering.py, mmpretrain/datasets/transforms/__init__.py, mmpretrain/datasets/transforms/utils.py, tools/misc/verify_dataset.py
=> [Fix][New_config] Fix demo bug 

configs/llava/README.md, configs/otter/README.md, configs/otter/otter-9b_caption.py, mmpretrain/models/multimodal/llava/llava.py, mmpretrain/models/multimodal/otter/otter.py
=> [Improve] Update Otter and LLaVA docs and config.

mmpretrain/models/backbones/vision_transformer.py
support to deal with cls_token
**Before PR**:
**After PR**:
=> [Refactor] Refactor _prepare_pos_embed in ViT

mmcls/utils/distribution.py
Fix the issue where 1p cannot specify a card number on Ascend NPU.
The mmcls/utils/distribution.py file is modified.
None.
None.
**Before PR**:
**After PR**:
=> [Fix]Fix the issue where 1p cannot specify a card number on Ascend NPU.

mmpretrain/configs/beit/beit_beit_base_p16_8xb256_amp_coslr_300e_in1k.py, mmpretrain/configs/convnext/convnext_base_32xb128_in1k_384px.py, mmpretrain/configs/eva/eva_mae_style_vit_base_p16_16xb256_coslr_400e_in1k.py, mmpretrain/configs/mae/mae_vit_base_p16_8xb512_amp_coslr_300e_in1k.py, mmpretrain/configs/resnet/resnet18_8xb32_in1k.py, mmpretrain/configs/simclr/simclr_resnet50_16xb256_coslr_200e_in1k.py
=> [Refactor] Replace `if '_base_'` with `read_base()`

mmpretrain/models/backbones/vision_transformer.py
=> [Fix] freeze pre norm in vision transformer

configs/mae/benchmarks/vit-huge-p14_8xb128-ds-coslr-50e_in1k.py, configs/mae/benchmarks/vit-huge-p14_8xb128-fsdp-coslr-50e_in1k.py, configs/mae/benchmarks/vit-large-p16_8xb128-ds-coslr-50e_in1k.py, configs/mae/benchmarks/vit-large-p16_8xb128-fsdp-coslr-50e_in1k.py
=> [Enhance] Update fsdp vit-huge and vit-large config

mmpretrain/datasets/transforms/processing.py
Fix bug refer to #1697 
**Before PR**:
**After PR**:
=> [Fix] Fix Wrong-paramer Bug of RandomCrop

mmpretrain/models/backbones/beit.py, mmpretrain/models/backbones/vision_transformer.py
=> [Refactor] BEiT refactor

configs/minigpt4/README.md, configs/otter/README.md, mmpretrain/models/multimodal/blip/blip_retrieval.py, mmpretrain/models/selfsup/simmim.py
Change `reprodcue` to `reproduce`. Change `backone` to `backbone`.
**Before …
=> [Refactor] Fix spelling

tools/visualization/vis_cam.py
Just a simple correction of a typo of 'target' in ```vis_cam.py```.
**Before PR**:
**After PR**:
=> [Fix] Typo fix of 'target' in vis_cam.py

mmpretrain/models/heads/multi_task_head.py, tests/test_models/test_heads.py
#1554 merged with the new version of dev
=> Nested predict

mmpretrain/models/multimodal/flamingo/flamingo.py, mmpretrain/models/multimodal/llava/llava.py, mmpretrain/models/multimodal/minigpt4/minigpt4.py, mmpretrain/models/multimodal/otter/otter.py, mmpretrain/models/utils/huggingface.py
Based on https://github.com/open-mmlab/mmengine/pull/1263
**Before PR**:
**After PR**:
=> [Enhance] Set 'is_init' in some multimodal methods

mmpretrain/models/multimodal/minigpt4/minigpt4.py
=> [Fix] Fix dict update in minigpt4

mmpretrain/datasets/__init__.py, mmpretrain/datasets/iconqa.py
=> Support IconQA dataset.

mmpretrain/datasets/__init__.py, mmpretrain/datasets/infographic_vqa.py, mmpretrain/evaluation/metrics/ANLS.py, mmpretrain/evaluation/metrics/__init__.py
=> Support Infographic VQA dataset and ANLS metric.

configs/_base_/models/mae_hivit-base-p16.py, configs/mae/mae_hivit-large-p16_8xb512-amp-coslr-400e_in1k.py
Fix a typo
Fix typo MIMHIVIT to MAEHiViT in two files
**Before PR**:
**After PR**:
=> [Fix] Fix typo MIMHIVIT to MAEHiViT

mmpretrain/datasets/coco_retrieval.py
=> [CodeCamp2023-341] 多模态数据集文档补充-COCO Retrieval
