open-mmlab/mmpretrain

- configs/_base_/datasets/imagenet_bs32.py
- configs/_base_/datasets/imagenet_bs32_pil_resize.py
- configs/_base_/datasets/imagenet_bs64.py
- configs/_base_/datasets/imagenet_bs64_pil_resize.py
Fix the parameter `size` of test_pipeline() in 'configs/base/datasets/*.py'. According to the docstring in https://github.com/open-mmlab/mmclassification/blob/408d92bcbe5f83c296e31ca0128b3d6521da7055/mmcls/datasets/pipelines/transforms.py#L336, we have to set `size=(256, -1)` to resize the short edge to 256 before center cropping.
> Fix the parameter `size` in test_pipeline

- mmcls/datasets/pipelines/transforms.py
CenterCrop transform currently crashes when the image is greyscale. This is because image shape has length 3 when the image is color but length two when the image is greyscale. The third element wasn't being used in either case, so this pull request modifies the code such that only the first two elements of image shape are unpacked.
> Fix crash in CenterCrop transform when image is greyscale

- demo/image_demo.py
- mmcls/apis/__init__.py
- mmcls/apis/inference.py
- mmcls/models/classifiers/base.py
- requirements/runtime.txt
Put predicted results as text on the input image, which may be easier for users to visualize the results.
> Visualize results on image demo

- .github/workflows/build.yml
Reverts open-mmlab/mmclassification#127, since new version of mmcv is avaliable.
> Revert "temporary solution to ci until new version of mmcv is avaliable"

- .pre-commit-config.yaml
- README.md
- docs/changelog.md
- mmcls/version.py
Hi,
Please kindly have a look at the following notes:
I assume the new version date is 2020.12.31? Pls correct me if I was wrong.
#112, #122 are not included since they fix bugs of evaluation metrics which is also released in this version.
#90 is included, but I am not quite sure whether it is appropriate. Should we instruct users on how to install mmcv in docs somewhere?
#102, #106, #115, #118 are not included since I assume replacing urls in model zoo, pre-commit hook, ci and links in docs should not be much of users' concerns?
And I disabled MD024 since it conflicts our current changelog style. I already checked other repos and made sure they have done the same.
> Bump version to 0.7.0

- .github/workflows/build.yml
- mmcls/core/evaluation/__init__.py
- mmcls/core/evaluation/mean_ap.py
- mmcls/core/evaluation/multilabel_eval_metrics.py
- tests/test_metrics.py
Add mAP, CP, CR, CF1, OP, OR, OF1 as multi-label task evaluation metrics:
1. Unittests are put in multilabel_eval_metrics.py temporarily, and I will put them in test_dataset.py once multi-label datasets are ready.
2. In papers, some report topk performance while others use threshold, so both methods are implemented for future convenience.
3. For mAP, the method provided by PASCAL VOC after 2010 is used.
> Add evaluation metrics for multilabel task

- mmcls/datasets/__init__.py
- mmcls/datasets/base_dataset.py
- mmcls/datasets/multi_label.py
- mmcls/datasets/voc.py
- tests/test_dataset.py
Hi,
This pull request supports dataset PASCAL VOC for multi-label task. Currently, only VOC2007 is supported.
Several details:
1. A MultiLabelDataset is implemented for future convenience since we plan to support other multi-label dataset, e.g. COCO. And it is not registered in DATASETS on purpose for it is not a complete dataset and we don't really want users to instantiate it.
2. The data format of gt_labels and cat_ids may vary from those of single-label multi-class task. 
3. Previously I promise to move test_metrics to test_dataset, however, now I doubt if that is a good idea. If I put them together, some parameter validity checks can not be covered. So I suggest that we should leave it as it was.
4. In the case where users only use a subset of VOC classes, a function that filters the …
> [Feature] Support PASCAL VOC 2007 dataset for multilabel task

- tools/analyze_results.py
Hi,
This pull request adds tools/analyze_results.py to select fix number of correctly/wrongly predicted imgs, sort them according to pred_score and save the info and painted images.
Please kindly take a look. Thx.
> [Feature] Add analyze_results.py to select imgs for success/fail

- mmcls/datasets/base_dataset.py
- mmcls/datasets/multi_label.py
- tools/test.py
Hi,
I have noticed that the metric_options argument in evaluate has different structure compared to other repos. And for different metrics, different metric_options should be set. So previously I intended to modify it to keep the consistency and make it clearer to users. 
However, for some metrics, e.g. CP, CR, CF1, OP, OR, OF1, it's weird to set different metric_options for them. So after consideration, I have decided to keep it the way as it is.
--eval-options is added in test.py and it is not merged with the config on purpose, because it seems unnatural to me to set --metrics but intend to use eval_options in config (because different metrics require different options). 
> [Feature] Add --eval-options in test.py

- tools/onnx2tensorrt.py
Add onnx2tensorrt in MMCls.
This PR includes:
1. A tool to create TensorRT engine from ONNX, run inference and verify outputs in Python.
This feature is based on `mmcv.tensorrt` from MMCV and requires to install TensorRT from source code. Please check [here](https://github.com/open-mmlab/mmcv/blob/master/docs/tensorrt_plugin.md#how-to-build-tensorrt-plugins-in-mmcv) for more information.
> [Feature]: add onnx2tensorrt

- setup.cfg
Hi, 
This pull request removes pytest configuration in setup.cfg. The current setting makes it inconvenient to specify test files when running pytest.
It seems to me that it should be set as `testpaths = tests/` instead of `addopts=tests/`, however that is also not necessary since the default `testpaths` is already `tests/`. So it is simply removed.
> [Fix] Remove pytest configuration in setup.cfg

- mmcls/datasets/pipelines/__init__.py
- mmcls/datasets/pipelines/auto_augment.py
- tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, Shear pipeline is added. 
This pull request serves as a sub-task for implementing auto-augmentation, therefore there are several things to note:
1. Most auto-augmentation implementation is based on pillow backend, however mmcv image transforms are mostly based on cv2 backend. After a comparison of those two, I found them different yet the difference is not awfully significant. Therefore I decided to first simply wrap mmcv transform in pipeline and see if the performance matches. 
2. Pipelines needed are listed below.
> [Feature] Add shear pipeline

- README.md
- docs/changelog.md
- mmcls/version.py
Hi Xiongyu,
Docs are updated for version 0.9.0 in this pull request.
#164 is skipped since it should not be of users' concerns.
> Bump version to 0.9.0 

- mmcls/datasets/pipelines/__init__.py
- mmcls/datasets/pipelines/auto_augment.py
- tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, Invert pipeline is added. In fact, invert is highly overlapped with solarize. But they are still implemented separately so that it is clearer to users. What do you say? @ycxioooong 
This pull request may have conflicts with #167, I will resolve them after #167 is merged.
> [Feature] Add invert pipeline

- mmcls/datasets/pipelines/__init__.py
- mmcls/datasets/pipelines/auto_augment.py
- tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, Solarize pipeline and Posterize pipeline are added. 
This pull request may have conflicts with #171, I will resolve them after #171 is merged.
Another thing to note is that when bumping version, we might need to update docs for version compatibility with mmcv accordingly.
> [Feature] Support solarize and posterize pipelines

- mmcls/apis/train.py
- mmcls/core/evaluation/eval_hooks.py
- tests/test_eval_hook.py
Hi,
This pull request uses EvalHook from mmcv(open-mmlab/mmcv#739) to replace ones in mmcls. Both are supported for mmcls v0.10.0, but the after that, `EvalHook` and `DistEvalHook` will be removed.
Pls kindly take a look. Thx.
> [Fix] Use MMCV's EvalHook in MMClassification

- tests/test_backbones/test_mobilenet_v2.py
1. frozen_stages and out_indices assertions are not the same as the assertions in the backbone.
2. Mis-position of BN and GN.
> Fix typo in unit test

- mmcls/apis/test.py
This PR fixed potential fatal errors when using mmclassification for testing/inference.
Current testing code will create a user-specified temp directory while deleting it after use.
The function does not stop if the temp directory exists and may accidentally delete original data in the folder.
This PR fixed it.
> Check if specified tmpdir exists when inference.

- mmcls/datasets/pipelines/auto_augment.py
- tests/test_pipelines/test_auto_augment.py
`magnitude_std` will introduce some randomness to policies, modified by https://github.com/rwightman/pytorch-image-models
Here is the instrument in the original repo:
```
```
> [Feature] Add RandAUG magnitude noise

- MANIFEST.in
Hi,
Previously, the MANIFEST.in fails to include mmcls/configs/\_base\_/\*/\*.py. This pull request fixes the issue. Thank you.
> [Fix]Fix MANIFEST.in

- mmcls/datasets/pipelines/auto_augment.py
- tests/test_pipelines/test_auto_augment.py
Hi,
In this pull request, we allow users to set magnitude range as `(max_val, min_val)` or `(min_val, max_val)`. Pls kindly take a look. Thank you.
> [Fix] Fix magnitude_range in RandAug

- mmcls/models/builder.py
This PR modifies the registry of models. It changes to inherit from MMCV registry, thus in the future OpenMMLab repos like MMDet and MMSeg could directly use the backbones supported in MMCls.
Related PR: https://github.com/open-mmlab/mmdetection/pull/5059, https://github.com/open-mmlab/mmsegmentation/pull/515
> [Refactor]: Inherits mmcv registry

- mmcls/apis/test.py
This PR fixes mmcls/apis/test.py that avoid potential directory operation conflicts. Now we only allow directory operation when `rank == 0`.
> [Fix] Only allow directory operation when rank==0 when testing

- mmcls/datasets/cifar.py
- mmcls/datasets/mnist.py
Hi,
Previously, when cifar/mnist dataset is not found locally, the dataset is downloaded on all ranks. However this not only wastes bandwidth but also causes error when the storage is shared among ranks. And this pull request fixes this issue by:
1. Download the dataset only on rank 0.
2. If shared storage is not avaliable, we raise an error and suggest that user shall download the dataset manually.
> [Bug] Download dataset only on rank 0

- configs/_base_/models/regnet/regnetx_1.6gf.py
- configs/_base_/models/regnet/regnetx_12gf.py
- configs/_base_/models/regnet/regnetx_3.2gf.py
- configs/_base_/models/regnet/regnetx_4.0gf.py
- configs/_base_/models/regnet/regnetx_400mf.py
- configs/_base_/models/regnet/regnetx_6.4gf.py
- configs/_base_/models/regnet/regnetx_8.0gf.py
- configs/_base_/models/regnet/regnetx_800mf.py
- configs/regnet/README.md
- configs/regnet/regnetx_1.6gf_b32x8_imagenet.py
- configs/regnet/regnetx_12gf_b32x8_imagenet.py
- configs/regnet/regnetx_3.2gf_b32x8_imagenet.py
- configs/regnet/regnetx_4.0gf_b32x8_imagenet.py
- configs/regnet/regnetx_400mf_b32x8_imagenet.py
- configs/regnet/regnetx_6.4gf_b32x8_imagenet.py
- configs/regnet/regnetx_8.0gf_b32x8_imagenet.py
- configs/regnet/regnetx_800mf_b32x8_imagenet.py
As discussed last week, we may need to add some pre-trained converted models.
Considering our repo supports RegNet already, but we don't have any config files, here I add RegNetX config files and pre-trained models from [Pycls model zoo](https://github.com/facebookresearch/pycls/blob/master/MODEL_ZOO.md#regnetx-models).
> Add RegNetX configs

- tools/train.py
Hi,
This pull request adds dumping config before training to align with other repos and makes it easier to reproduce experiments. Thx.
> [Feature]Dump config before training

- mmcls/apis/test.py
- tools/test.py
Hi,
In this pull request, a bug is fixed. 
Previously, if we do not round up the data, when num_imgs can not be evenly divided by num_gpus, results for some imgs might be accidentally loss and finally cause assertion error when we check `len(gt_labels) == len(results)`. In this way, previous check of whether `part_result` is unnecessary since all rank shall have the same length of `part_result`.
Pls kindly take a look. Thank u.
> [Bug] Missing test data when num_imgs can not be evenly divided by num_gpus

- mmcls/models/losses/label_smooth_loss.py
- tests/test_losses.py
Now, label smooth loss accepts a parameter `mode`. It can be one of "original", "classy_vision" and "multi_label" and use the corresponding method to calculate smoothing labels.
> Refactor LabelSmoothLoss

- docs/tutorials/pytorch2torchscript.md
- mmcls/models/heads/cls_head.py
- mmcls/models/heads/linear_head.py
- mmcls/models/heads/multi_label_head.py
- mmcls/models/heads/multi_label_linear_head.py
- mmcls/models/heads/vision_transformer_head.py
- tools/deployment/pytorch2torchscript.py
Hi, this is a PR for mim installing mmclassification with pytorch v1.3-v1.5.
torch.jit.is_tracing() is supported after pytorch v1.6. For pytorch v1.3-v1.5, mim installing mmclassification will fail like [this](https://github.com/open-mmlab/mim/pull/39/checks?check_run_id=2811922234#step:9:242).
> [Fix] Build compatible with low pytorch versions

- mmcls/models/heads/linear_head.py
- mmcls/models/heads/multi_label_linear_head.py
Use parameter default value to control default behavior of init_cfg in `LinearClsHead`. After that, we can suppress this default value by passing `init_cfg=None` in the config file.
And remove the verbose `_init_layers` method of `LinearClsHead`.
> Use parameter default value to control default behavior of init_cfg in `LinearClsHead`.

- mmcls/models/classifiers/image.py
when I define 
```
samples_per_gpu=1,
workers_per_gpu=0,
```
in configs/lenet/lenet5_mnist.py.
An  error  occurred:
>   ..............
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/classifiers/base.py", line 73, in forward_test
>     return self.simple_test(imgs[0], **kwargs)
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/classifiers/**image.py**", line 81, in simple_test
>     return self.head.simple_test(x)
>   File "/home/n/Github/mmclassification0110/mmclassification/mmcls/models/heads/cls_head.py", line 64, in simple_test
>     pred = F.softmax(cls_score, dim=1) if cls_score is not None else None
>   File "/home/n/anaconda3/envs/pytorch130/lib/python3.7/site-packages/torch/nn/functional.py", line 1231, in softmax
>     ret = …
> fix a bug when samples_per_gpu==1

- mmcls/models/heads/cls_head.py
- mmcls/models/heads/linear_head.py
- mmcls/models/heads/multi_label_head.py
- mmcls/models/heads/multi_label_linear_head.py
- mmcls/models/heads/vision_transformer_head.py
- mmcls/models/utils/__init__.py
- mmcls/models/utils/helpers.py
In PyTorch 1.6, `torch.jit.is_tracing` returns an object by mistake. Refers to https://github.com/pytorch/pytorch/issues/42448#issue-671987165
Here I add a helper function `is_tracing` to avoid it. And use this function in all heads.
> [Fix] Fix a tracing bug in PyTorch 1.6

- mmcls/datasets/builder.py
1. Support the `presistent_works` option if PyTorch version >= 1.7.0, and use it by default. Refers to https://github.com/open-mmlab/mmaction2/pull/998
2. Support the `pin_memory` option.
> [Feature] Support two options in `build_dataloader`.

- configs/resnet/resnet50_b64x32_warmup_label_smooth_imagenet.py
The base link in `resnet50_b64x32_warmup_label_smooth_imagenet.py` is broken, now fix it.
> [Fix] Fix broken _base_ link in a resnet config.

- mmcls/models/backbones/vision_transformer.py
Remove duplicate `init_weights` call in ViT.
This will cause `init_weights` to fail in latest `mmcv==1.3.10`
> [Fix] Fix duplicate `init_weights` call in ViT init function.

- mmcls/models/builder.py
- mmcls/models/utils/attention.py
Refers to https://github.com/open-mmlab/mmclassification/issues/369.
> [Fix] Use local ATTENTION registry to avoid conflict with other repo.

- docs_zh-CN/tutorials/MMClassification_python_cn.ipynb
- docs_zh-CN/tutorials/MMClassification_tools_cn.ipynb
The `Open in colab` is wrong, now fix it.
You can read it in Colab now:
[MMClassification_python_cn](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs_zh-CN/tutorials/MMClassification_python_cn.ipynb)
[MMClassification_tools_cn](https://colab.research.google.com/github/open-mmlab/mmclassification/blob/master/docs_zh-CN/tutorials/MMClassification_tools_cn.ipynb)
> [Docs] Fix `Open in colab` link in Colab tutorials.

- docs/conf.py
In response to urgent needs, #382 and #383 are merged forcibly, skipping CI. This PR is to fix some lint errors in those PRs.
Apply lint and fix the error.
> [Docs] Fix readthedocs config lint

- mmcls/datasets/imagenet.py
Implementation of the `ImageNet` dataset contains duplicated operations: one extra call of `os.listdir` and calls of `os.path.isdir` for every class folder in the dataset. Since this loader can be used for much more larger datasets than ImageNet, it should be as effective as possible. In pytorch's ImageFolder dataset which is basically pretty close to the considered `ImageNet` class, these duplications are eliminated. 
Duplicated calls were eliminated (all the top level folder structure checks are concentrated in `find_folders`).
This PR doesn't brake anything.
> [Enhance] Avoid unnecessary `listdir` when building `ImageNet`

- requirements/optional.txt
Our optional dependency `albumentations` may install both `opencv` and `opencv-headless`. Refers to [the docs](https://albumentations.ai/docs/getting_started/installation/#note-on-opencv-dependencies).
This PR updates the installation of `albumentations` to prevent using a wheel distribution of it with `opencv-headless `dependency. Refers to https://github.com/open-mmlab/mmpose/pull/833
No
**Before PR**:
**After PR**:
> [Fix] Avoid installing both opencv and opencv-headless.

- mmcls/models/heads/cls_head.py
- mmcls/models/heads/linear_head.py
- mmcls/models/heads/multi_label_head.py
- mmcls/models/heads/multi_label_linear_head.py
- mmcls/models/heads/stacked_head.py
- mmcls/models/heads/vision_transformer_head.py
In most heads, we need to do some post-processing after getting the pred result. However, downstream tasks, like deploy, may want to override this post-processing function.
Convert the post-processing in the `simple_test` function to a standalone method. And all child classes can reuse the method.
No.
**Before PR**:
**After PR**:
> [Refactor] Use `post_process` function to handle pred result processing.

- mmcls/datasets/base_dataset.py
Fixing a typo so that the code becomes more clear.
I've changed the typo 'metirc' to 'metric' in mmcls/datasets/base_dataset.py
**Before PR**:
**After PR**:
> [Fix] Fix typo 'metirc'

- configs/_base_/datasets/imagenet_bs64_swin_224.py
- configs/_base_/datasets/pipeline/rand_aug.py
- configs/_base_/datasets/pipelines/rand_aug.py
- mmcls/datasets/pipelines/auto_augment.py
- tests/test_data/test_pipelines/test_auto_augment.py
In `AutoAugment` and `RandAugment`, there are many common arguments in sub-policies. Now we have to set these arguments one by one.
1. Add `hparams` argument in `AutoAugment` and `RandAugment`, so that we can specify common arguments by once.
2. Use `hparams` and [base variable](https://github.com/open-mmlab/mmcv/pull/1083) to simplify `RandAug` settings in swin-transformer.
2. Now `pad_val` supports using `Sequence` instead of only `tuple`.
3. Use smaller test images to speed up unit tests.
No.
```python
>>> policies = [
...     dict(
...         type='Translate',
...         magnitude_key='magnitude',
...         magnitude_range=(0, 1),
...         pad_val=128,
...         direction='horizontal'),
...     dict(
...         type='Rotate',
...         magnitude_key='angle',
... …
```
> [Enhance] Add `hparams` argument in `AutoAugment` and `RandAugment` and some other improvement.

- mmcls/apis/inference.py
- mmcls/core/visualization/__init__.py
- mmcls/core/visualization/image.py
- mmcls/models/classifiers/base.py
- setup.cfg
- tests/test_models/test_classifiers.py
- tests/test_utils/test_visualization.py
Now, our `show_result_pyplot` doesn't support `wait_time`. And it uses OpenCV as the `imshow` backend, which may cause some problems, refers to https://github.com/open-mmlab/mmdetection/pull/4389
Modify the visualization APIs and code structure as mmdet style.
No
Use demo as example:
```shell
python demo/image_demo.py demo/demo.JPEG config/resnet/resnet50_b32x8_imagenet.py resnet50.pth
```
**Before PR**:
**After PR**:
> [Enhance] Better result visualization

- tools/analysis_tools/analyze_results.py
- tools/test.py
- tools/train.py
In our tools, the name of the option for updating config is not united. Refers to [mmdet](https://github.com/open-mmlab/mmdetection/pull/3537), we unify them as `--cfg-options` because there are also `--metrics-options` or `--show-options`.
As the title, modify `tools/test.py`, `tools/train.py` and `tools/analysis_tools/analyze_results.py`.
And I rename `--gpu_collect` to `--gpu-collect`, it should be a typo.
Almost not, and I reserved the original option `--options`.
**Before PR**:
**After PR**:
> [Enhance] Rename the option `--options` in some tools to `--cfg-options`.

- CITATION.cff
- setup.py
Github provides the citation option now, and to use it, we need to add `CITATION.cff`.
As the title.
And fix some small typo in `setup.py`, change `author` in `setup.py`. Refers to https://github.com/open-mmlab/mmtracking/pull/253
The auto generated bib file:
```bib
@misc{MMClassification_Contributors_OpenMMLabs_Image_Classification_2020,
author = {{MMClassification Contributors}},
month = {7},
title = {{OpenMMLab's Image Classification Toolbox and Benchmark}},
url = {https://github.com/open-mmlab/mmclassification},
year = {2020}
}
```
**Before PR**:
**After PR**:
> [Docs] Add `CITATION.cff`

- tools/analysis_tools/analyze_results.py
- tools/analysis_tools/eval_metric.py
- tools/test.py
The out file of our `tools/test.py` includes all detailed information, like class scores, pred_label, pred_score, pred_class of each sample.
As the result, a huge dataset leads to a huge result file, and not all data is necessary.
Add an `--out-items` option, users can use it to specify which info should be included in the result file.
```shell
python tools/test.py configs/resnet/resnet18_b16x8_cifar10.py ckpt.pth --metrics accuracy --out result.pkl --out-items class_scores pred_label
```
and
```python
>>> import mmcv
>>> res = mmcv.load("./result.pkl")
>>> print(res.keys())
dict_keys(['accuracy_top-1', 'accuracy_top-5', 'class_scores', 'pred_label'])
```
**Before PR**:
**After PR**:
> [Enhance] Support setting `--out-items` in `tools/test.py`. 

- mmcls/models/backbones/tnt.py
- mmcls/models/classifiers/image.py
- tests/test_models/test_backbones/test_tnt.py
TnT does not support return tuple now. And the warning in `extract_feat` will show in every call.
As the title
**Before PR**:
**After PR**:
> [Refactor] Fix TnT compatibility and verbose warning.

- tools/deployment/pytorch2onnx.py
Now in `pytorch2onnx.py`, we get `num_classes` from `model.head`. But if models use `ClsHead`, `num_classes` is from `backbone`. Refers to #442
Check if `model.head` doesn’t have `num_classes`, try to find it in `model.backbone`.
No
No
**Before PR**:
**After PR**:
> [Fix] Fix num_classes bug in pytorch2onnx.py

- tools/convert_models/publish_model.py
Now, we use `os.path.dirname` to get the parent of `out_file`. However, if we use `out_file` like `resnet.pth`, the `os.path.dirname` gets an empty string, and `os.path.exists` gets False.
Use `pathlib` to replace `os.path`.
No
No.
**Before PR**:
**After PR**:
> Fix `publish_model` bug if no parent of `out_file`.

- tools/test.py
Fix the output format error when --metric-options average_mode=none
Add metric-options judgment condition
**Before PR**:
**After PR**:
> [Fix] Fix format error in `test.py` when metric returns `np.ndarray`

- tools/analysis_tools/analyze_logs.py
Make `analyze_log.py` works with single validation iteration. Currently, the `analyza_logs.py` use `iters = iters[:-1]` to get rid of the last validation iteration, but in a very small `val` set, there maybe only one validation step. In such case, the `analyze_log.py` won't work, it use print out a blank figure. This PR fixed that. 
When there is only one item in the `iters` list, then don't slice it.
**Before PR**:
**After PR**:
> [Fix] Fix wrong condition judgment in `analyze_logs.py` and prevent empty curve.

- tools/analysis_tools/analyze_results.py
The output json file from the `test.py` script could contain scalar item, but the `analyze_result.py` presumes the item from the result json is a list. This PR filter the scalar item before indexing them.
**Before PR**:
**After PR**:
> [Fix] Fix an error on indexing scalar metrics in `analyze_result.py`

- mmcls/datasets/pipelines/__init__.py
- mmcls/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform.py
This pull request is base on issue#453
Refactor the `Resize` to enable resizing images while keeping the aspect ratio with padding.
> [Refactor] Refactor `Resize` transform and add `Pad` transform.

- mmcls/models/heads/cls_head.py
- mmcls/models/heads/linear_head.py
- mmcls/models/heads/multi_label_head.py
- mmcls/models/heads/multi_label_linear_head.py
- mmcls/models/heads/stacked_head.py
- mmcls/models/heads/vision_transformer_head.py
- tests/test_models/test_heads.py
the forward function of loss(CE, Focal Loss and etc) have parameters like `weight` and so on. but users can not pass `weight` by using function head.forward_train.
Add **kwargs in heads, and add kwargs in loss function in Clshead.
No.
```
weight = torch.tensor( [0.5, 0.5] )
head.forward_train(imgs, gt_labels, weight=weight........)
```
**Before PR**:
**After PR**:
> [Refactor] Support passing arguments to loss from head.

- mmcls/models/losses/cross_entropy_loss.py
- tests/test_metrics/test_losses.py
Add pos_weight in BCE
Add pos_weight in BCE
no
```
pos_weight = [0.1, 0.2]
loss_cfg = dict(
type='CrossEntropyLoss',
use_sigmoid=True,
reduction='mean',
loss_weight=1.0,
pos_weight=pos_weight)
loss = build_loss(loss_cfg)
```
**Before PR**:
**After PR**:
> [Feature] Support positive weights in BCE.

- mmcls/apis/inference.py
Refers to https://github.com/open-mmlab/mmdetection/pull/6405
When loading a checkpoint, map the checkpoint to the CPU, instead of `None` in a multi-GPUs environment.
No
No
**Before PR**:
**After PR**:
> [Fix] Fix a bug when load checkpoints in mulit-GPUs environment.

- mmcls/models/backbones/timm_backbone.py
- tests/test_models/test_backbones/test_timm_backbone.py
Some of timm models have different name of classifier. For example vision transformer's classifier name is [head](https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/vision_transformer.py#L293). 
And timm has 'reset_classifier' to fix classifier. So it looks better to use it.
Using `reset_classifier` to make unused parameters `nn.Identity`.
Add test to check `global_pool` and `classifier` is nn.Identity.
No.
**Before PR**:
**After PR**:
> [Refactor] Use `reset_classifier` to remove head of timm backbones.

- README.md
- README_zh-CN.md
- docs/conf.py
- docs_zh-CN/conf.py
Since mmflow is released, add it to README and banner.
As the title
**Before PR**:
**After PR**:
> [Docs] Add mmflow and mim in banner and readme

- mmcls/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform.py
`mmcv.imresize` with `pillow` backend support different interpolation methods with `cv2` ones. Interpolation method checking in `Resize` raise an error for some of the use case, e.g. `Resize(size=SIZE, interpolation='box', backend='pillow')`.
Perform an interpolation method check for pillow backend and cv2 backend, respectively.
**Before PR**:
**After PR**:
> [Fix] Fix interpolation method checking in `Resize`

- mmcls/models/classifiers/base.py
- tests/test_models/test_classifiers.py
fix bug when using iterbaserunner with 'val' workflow. refer to #535 
Align the train_step and val_step with [epochBaseRunner](https://github.com/open-mmlab/mmcv/blob/add157cc73b05c7be3d9b63505e17dc2288a6d0f/mmcv/runner/epoch_based_runner.py#L29)  and [iterBaseRunner](https://github.com/open-mmlab/mmcv/blob/master/mmcv/runner/iter_based_runner.py) in mmcv 
add a default value None for optimizer
add kwargs
**Before PR**:
**After PR**:
> fix bug when using iterbaserunner with 'val' workflow

- tools/analysis_tools/eval_metric.py
- tools/misc/print_config.py
- tools/visualizations/vis_pipeline.py
Now mmcv can handle `custom_imports`, so we don't need `import_modules_from_string`.
As the title.
**Before PR**:
**After PR**:
> [Refactor] Remove useless `import_modules_from_string`.

- mmcls/models/backbones/swin_transformer.py
- tests/test_models/test_backbones/test_swin_transformer.py
For larger batch size training in swin transformer.
Added checkpointing in swin transformer.
**Before PR**:
**After PR**:
> [Feature] Support using checkpoint in Swin Transformer to save memory. 

- mmcls/core/visualization/image.py
- tests/test_utils/test_visualization.py
- tools/visualizations/vis_pipeline.py
In matplotlib 3.5, the `matplotlib.blocking_input` module has been deprecated, which refers to this [link](https://github.com/anntzer/matplotlib/blob/b2a7521f69a8d9b08beffef9fc31fbf555e93abf/doc/api/next_api_changes/deprecations/20208-AL.rst).
Closing #566.
- As the title.
- And add a return value to `BaseFigureContextManager.wait_continue()` to indicate whether the user presses the continue key or closes the figure.
- In `tools/visualizations/vis_pipeline.py`, the progress will be interrupted if the user closes the show figure.
If users use the return value of `ImshowInfosContextManager.put_img_infos`, they need a small modification, from
```python
img = manager.put_img_infos(img, {'info': 'text'})
```
to
```python
_, img = manager.put_img_infos(img, {'info': 'text'})
```
**Before PR**: …
> [Refactor] Use new API of matplotlib to handle blocking input in visualization.

- mmcls/apis/__init__.py
- mmcls/apis/train.py
- tools/train.py
Refers to https://github.com/open-mmlab/mmdetection/pull/6457
When the seed is not set in the args, it will randomly generate a seed and broadcast to all ranks.
**Before PR**:
**After PR**:
> [Enchance] Set a random seed when the user does not set a seed.

- mmcls/models/backbones/swin_transformer.py
- tests/test_models/test_backbones/test_swin_transformer.py
fix bug;
layer_norm 0,1,2,3  will be the same and resulted in an error when out_indices dict exceed one element. for example out_indices = (0,1,2,3)
**Before PR**:
**After PR**:
> [Fix] Fix a bug for multiple output in swin transformer.

- setup.py
Refers to https://github.com/open-mmlab/mmflow/pull/37
Related Issue: [open-mmlab/mmdetection#6480](https://github.com/open-mmlab/mmdetection/issues/6480)
Creating a symbolic link on windows may raise an OSError: [WinError 1314] due to privilege. If the error happens, the src file will be copied.
> [Enhance] Try to create a symbolic link on windows.

- docker/Dockerfile
- docs/install.md
- docs_zh-CN/install.md
Update mmcv,torch,cuda version in Dockerfile and doc
docker/Dockerfile
install.md
**Before PR**:
**After PR**:
> [Fix] Update mmcv,torch,cuda version in Dockerfile and doc

- mmcls/models/losses/accuracy.py
- tests/test_metrics/test_metrics.py
The original `accuracy_numpy` needs twice sort which costs large memory and time if the number of classes is large.
1. Use better methods to improve `accuracy_numpy`'s performance.
2. Fix a bug in accuracy calculation.
**Before PR**:
**After PR**:
> [Enhance] Improve accuracy calculation performance.

- mmcls/core/__init__.py
- mmcls/core/optimizers/__init__.py
- mmcls/core/optimizers/lamb.py
- tests/test_runtime/test_optimizer.py
The 'ResNet Strikes Back' requires `LAMB` optimizer
Add LAMB optimizer
> [Feature] LAMB optimizer

- mmcls/core/evaluation/eval_metrics.py
- mmcls/datasets/base_dataset.py
- mmcls/models/losses/accuracy.py
- tests/test_metrics/test_metrics.py
Test on data shape: (50000, 1000), which is the validation set size of ImageNet.
| metric | original speed (ms) | new speed (ms) |
| :-------:| :--:| :--: |
| accuracy | 76.7 | 17.9 |
| precision / recall / f1_score | 3770 | 201 |
| support | 531 | 15.5 |
The return value of accuracy is changed to `float | list[float] | list[list[float]]`, which is unified with other metrics. And according to the docstring of accuracy, it should be float, but the original return value is wrong.
**Before PR**:
**After PR**:
> [Enhance] Imporve efficiency of precision, recall, f1_score and support.

- mmcls/utils/__init__.py
- mmcls/utils/logger.py
- tests/test_utils/test_logger.py
- tools/analysis_tools/analyze_logs.py
The structure of `load_json_logs`'s output is too complex.
Change it to `load_json_log` and fix docstring.
**Before PR**:
**After PR**:
> [Refactor] Change `load_json_logs` to `load_json_log`.

- README.md
- README_zh-CN.md
- docs/en/install.md
- docs/zh_CN/install.md
We have changed our development workflow and now we develop on the `dev` branch. Therefore we need to update our install guide.
1. Update install guide.
2. Update README, use readthedocs link preferentially. And add new repos.
**Before PR**:
**After PR**:
> [Docs] Update install guide and README

- tools/train.py
Currently, `mmcls` only save class names of dataset in `checkpoint` hook by populate the `meta` dictionary in here:
https://github.com/open-mmlab/mmclassification/blob/5232965b17b6c050f9b328b3740c631ed4034624/tools/train.py#L164
At the meantime, the `evaluation` hook use the `meta` dictionary form the runner which doesn't contains the classes name information, so the best checkpoint created by the `evaluation` hook won't contains `CLASSES` key. This is not very user friendly for training model on custom dataset because the test will load the `ImageNet` categories if the `CLASSES` key is missed in the `meta` dictionary of the checkpoint.
https://github.com/open-mmlab/mmclassification/blob/5232965b17b6c050f9b328b3740c631ed4034624/tools/test.py#L156
Populate the class names of training …
> [Refactor] Save class names in best checkpoint created by evaluation hook

- tools/deployment/pytorch2mlmodel.py
Convert the models to `mlmodel` format, which can be used in Apple devices.
The script is based on the existing `pytorch2torchscript.py` and [coremltools](https://github.com/apple/coremltools) library.
Another, specific way to deploy models for apple devices. 
Useful for e.g. if one deploys on iPhone apps that should work without an internet connection.
If you think this makes sense, I can write the corresponding docs as well.
> [Feature] add conversion script from pytroch to mlmodel

- mmcls/datasets/__init__.py
- mmcls/datasets/base_dataset.py
- mmcls/datasets/builder.py
- mmcls/datasets/dataset_wrappers.py
- mmcls/datasets/multi_label.py
- tests/test_data/test_builder.py
- tests/test_data/test_datasets/test_dataset_wrapper.py
- tools/kfold-cross-valid.py
K-Fold cross-validation is commonly used in small dataset training. Here we add the support of the K-fold dataset wrapper.
Closing #560 
1. Add a new dataset wrapper, `KFoldDataset`.
2. Support to use `indices` to specify which samples to evaluate.
No
Here we modify the [resnet18_8xb32_in1k.py](https://github.com/open-mmlab/mmclassification/blob/master/configs/resnet/resnet18_8xb32_in1k.py) as an example.
```python
_base_ = [
'../_base_/models/resnet18.py',
'../_base_/schedules/imagenet_bs256.py', '../_base_/default_runtime.py'
]
dataset_type = 'ImageNet'
img_norm_cfg = dict(
mean=[123.675, 116.28, 103.53], std=[58.395, 57.12, 57.375], to_rgb=True)
train_pipeline = [
dict(type='LoadImageFromFile'),
dict(type='RandomResizedCrop', size=224),
dict(type='RandomFlip', flip_prob=0.5, …
```
> [Feature] Support K-fold cross-validation

- mmcls/models/losses/asymmetric_loss.py
- tests/test_metrics/test_losses.py
The current implementation of asymmetric loss is hard-coded to work for only multi-label task with sigmoid and fixed eps value. 
By this modification, users can use asymmetric loss for single-label task and/or specified eps value.
Support single-label, softmax, custom eps by asymmetric loss.
This modification keeps backward compatibility.
- Use asymmetric loss for single-label tasks
- Use asymmetric loss with user-specified eps value for multi-label or single-label tasks
**Before PR**:
- [x ] Pre-commit or other linting tools are used to fix the potential lint issues.
- [x ] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [x ] The modification is covered by complete unit tests. If not, please add more unit test to ensure the …
> [Enhance] Support single-label, softmax, custom eps by asymmetric loss

- mmcls/models/backbones/timm_backbone.py
- tests/data/retinanet.py
- tests/test_downstream/test_mmdet_inference.py
- tests/test_models/test_backbones/test_timm_backbone.py
See the discussion in https://github.com/open-mmlab/mmdetection/pull/7020. In MMDet, MMSeg, and other downstream repos, we wish to directly use backbones supported by TIMM in MMCls. Therefore, it is necessary to support this option for downstream tasks.
This PR will close https://github.com/open-mmlab/mmclassification/issues/665.
This PR (especially `test_timm_backbone_features_only`) is based on https://github.com/open-mmlab/mmsegmentation/pull/998.
Here is an example config `retinanet_timm_tv_resnet50_fpn_fp16_4x4_1x_coco.py`.
The results at epoch 1 (`bbox_mAP_copypaste: 0.162 0.285 0.164 0.084 0.201 0.201`) are similar to those of `retinanet_r50_fpn_fp16_1x_coco.py` ([`bbox_mAP_copypaste: 0.164 0.284 0.168 0.082 0.189 0.203`](https://download.openmmlab.com/mmdetection/v2.0/fp16/retinane …
> [Feature] Support features_only in TIMMBackbone

- requirements/optional.txt
- setup.py
Refers to https://github.com/open-mmlab/mmcv/pull/1637
Update the setup.py
**Before PR**:
**After PR**:
> [Refactor] Deprecate the support for "python setup.py test"

- mmcls/utils/__init__.py
- mmcls/utils/setup_env.py
- setup.cfg
- tests/test_utils/test_setup_env.py
- tools/test.py
- tools/train.py
Refers to https://github.com/open-mmlab/mmdetection/pull/7036
According to some tests, these setup items can avoid some problems which slow down the training speed. Test on mmcls will be added after.
Add setup multi-processing both in train and test.
Add unit tests.
**Before PR**:
**After PR**:
> [Enhance] Add setup multi-processing both in train and test.

- docs/en/getting_started.md
- docs/zh_CN/getting_started.md
- mmcls/apis/train.py
- tools/test.py
- tools/train.py
Refers to https://github.com/open-mmlab/mmdetection/pull/7016, and it's based on https://github.com/open-mmlab/mmcv/pull/1621
As the title.
No, the old style is reserved but deprecated and it will be removed after three months.
Old style CPU training
```shell
python tools/train.py $CONFIG --device cpu
```
New style CPU training
```shell
export CUDA_VISIBLE_DEVICES=-1
python tools/train.py $CONFIG
```
**Before PR**:
**After PR**:
> [Enhance] New-style CPU training and inference.

- tools/kfold-cross-valid.py
- tools/test.py
- tools/train.py
Refers to https://github.com/open-mmlab/mmdetection/pull/7019
As the title.
**Before PR**:
**After PR**:
> [Refactor] Use `--gpu-id` instead of `--gpu-ids` in non-distributed multi-gpu training/testing

- .pre-commit-config.yaml
- mmcls/apis/train.py
- mmcls/core/optimizers/__init__.py
- mmcls/core/visualization/__init__.py
- mmcls/core/visualization/image.py
- mmcls/datasets/builder.py
- mmcls/models/backbones/conformer.py
- mmcls/models/backbones/repvgg.py
- mmcls/models/utils/augment/utils.py
- setup.cfg
- tests/data/retinanet.py
- tests/test_data/test_builder.py
- tests/test_data/test_pipelines/test_auto_augment.py
- tests/test_models/test_backbones/test_efficientnet.py
- tests/test_models/test_backbones/test_repvgg.py
- tests/test_models/test_utils/test_se.py
- tests/test_runtime/test_hooks.py
- tests/test_runtime/test_num_class_hook.py
- tests/test_runtime/test_optimizer.py
- tests/test_runtime/test_preciseBN_hook.py
- tools/deployment/onnx2tensorrt.py
- tools/deployment/pytorch2onnx.py
- tools/visualizations/vis_cam.py
Our `isort` hook is outdated, use new version isort hook.
As the title.
**Before PR**:
**After PR**:
> [Enhance] Upgrade isort pre-commit hooks.

- tools/deployment/onnx2tensorrt.py
- tools/deployment/pytorch2onnx.py
- tools/deployment/test.py
Since [MMDeploy](https://github.com/open-mmlab/mmdeploy) has been released, the deployment tools scattered in each OpenMMLab codebase will be deprecated in future.
Add deprecation message in deployment tools.
Used package [colorama](https://github.com/tartley/colorama#colored-output) to print cross-platform colored text.
None
And the message would look like it in Ubuntu18.04 terminal:
> Add deprecation message for deploy tools

- configs/convnext/README.md
- configs/convnext/metafile.yml
Add converted ConvNeXt pretrain models on in1k dataset for downstream tasks from origin repo.
**Before PR**:
**After PR**:
> [Enhance] Add ConvNeXt pretrain models on ImageNet-1k

- mmcls/models/backbones/conformer.py
- tests/test_models/test_backbones/test_conformer.py
Fix #680 
Use `AdaptivePadding` to pad the stem feature map to be divisible by 4.
**Before PR**:
**After PR**:
> [Fix] Fix Conformer forward with irregular input size.

- .github/workflows/build.yml
- mmcls/datasets/base_dataset.py
- mmcls/datasets/builder.py
- mmcls/datasets/dataset_wrappers.py
- tools/test.py
Our ConcatDataset doesn't support evaluation by now.
As the title
For `separate_eval=True`:
```python
data = dict(
...
test = [dict(type='ImageNet', data_prefix='data1', ...),
dict(type='ImageNet', data_prefix='data2', ...)],
)
```
The test output:
```
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 57000/57000, 478.1 task/s, elapsed: 119s, ETA:     0s
2022-01-17 10:50:17,439 - mmcls - INFO - Evaluateing dataset-0 with 7000 images now
2022-01-17 10:50:17,456 - mmcls - INFO - Evaluateing dataset-1 with 50000 images now
0_accuracy_top-1 : 81.13
0_accuracy_top-5 : 95.27
1_accuracy_top-1 : 69.9
1_accuracy_top-5 : 89.43
```
For `separate_eval=False`:
```python
data = dict(
...
test = dict(
type='ConcatDataset',
datasets=[dict(type='ImageNet', data_prefix='data1', ...), …
```
> [Feature] Add `evaluate` function for ConcatDataset

- docs/en/getting_started.md
- docs/zh_CN/getting_started.md
- tools/dist_test.sh
- tools/dist_train.sh
refer to https://github.com/open-mmlab/mmselfsup/pull/232
On the first machine:
```shell
NNODES=2 NODE_RANK=0 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR sh tools/dist_train.sh $CONFIG $GPUS
```
On the second machine:
```shell
NNODES=2 NODE_RANK=1 PORT=$MASTER_PORT MASTER_ADDR=$MASTER_ADDR sh tools/dist_train.sh $CONFIG $GPUS
```
**Before PR**:
**After PR**:
> [Feature] Add multi machine dist_train

- docs/zh_CN/conf.py
When i read the mmclassification zh_CN docs, i click the logo on left top, which redirect me to mmocr.readthedocs.io, after reading the source, i find it was a little bug
i modify the file in docs/zh_CN/conf.py :91, and modify the link from `https://mmocr.readthedocs.io/zh_CN/latest/` to `https://mmclassification.readthedocs.io/zh_CN/latest/`
No
No
**Before PR**:
**After PR**:
> [Docs] Fix logo url link from mmocr to mmclassification.

- mmcls/datasets/dataset_wrappers.py
- tests/test_data/test_datasets/test_dataset_wrapper.py
KFoldDataset isn't implemented get_cat_ids and get_gt_labels.
Not implemented get_cat_ids, KFoldDataset can't use with ClassBalancedDataset for example.
Not implemented get_gt_labels, can't calculate confusion matrix like #598.
Simply implemented these methods to KFoldDataset.
**Before PR**:
**After PR**:
> [Enhance] Add get_cat_ids and get_gt_labels to KFoldDataset

- mmcls/models/backbones/convnext.py
The output feature map of ConvNeXt may be not contiguous, which may cause training problem in downstream tasks.
Make the output feature map be contiguous.
**Before PR**:
**After PR**:
> [Fix] Fix the discontiguous output feature map of ConvNeXt.

- README.md
- README_zh-CN.md
This is an implantation from MMEditing [#816](https://github.com/open-mmlab/mmediting/pull/816) 
**Before PR**:
**After PR**:
> [Docs] Add brief installation steps in README for copy&paste

- mmcls/apis/train.py
- tools/test.py
In some situation, we need to use different dataloader settings like `samples_per_gpu` in train/val/test dataloader.
Use `train_dataloader`, `val_dataloader` and `test_dataloader` settings in the `data` field to specify different arguments.
```python
data = dict(
samples_per_gpu=64,
workers_per_gpu=4,
train=dict(type='xxx', ...),
val=dict(type='xxx', ...),
test=dict(type='xxx', ...),
val_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
test_dataloader=dict(samples_per_gpu=8, workers_per_gpu=2),
)
```
**Before PR**:
**After PR**:
> [Enhance] Add extra dataloader settings in configs.

- mmcls/models/utils/position_encoding.py
For position_encoding, the **self.proj**'s input is always a non-contiguous tensor, there has a performance issue when **self.stride == 1**, because PyTorch always has a contiguous conversion when convolution's input is not a contiguous tensor(https://github.com/pytorch/pytorch/blob/fa09099ba35fcd42347732ca3a5f8ddaf145da1b/aten/src/ATen/native/Convolution.cpp#L1093), and **add** also has a similar issue(the input from convolution is a contiguous tensor, but another input is non-contiguous tensor).
This PR will do pre contiguous conversion before doing **convolution** and **add** computing.
> [Enhance] Improve CPE performance by reduce memory copy.

- mmcls/models/backbones/swin_transformer.py
- mmcls/models/utils/__init__.py
- mmcls/models/utils/embed.py
> [Feature] Support resize relative position embedding in `SwinTransformer`.

- tests/test_models/test_backbones/test_swin_transformer.py
Closing #758 
Use 1 instead of 3 as batch size in unit tests for Swin-Transformer.
**Before PR**:
**After PR**:
> [Enhance] Reduce the memory usage of unit tests for Swin-Transformer

- .github/workflows/test-mim.yml
refers to https://github.com/open-mmlab/mmsegmentation/pull/1654/files
> [CI] Add test mim CI.

- mmcls/datasets/pipelines/transforms.py
- tests/test_data/test_pipelines/test_transform.py
When I use Albu for dataset aug, It cause error :
I debug and found out that becuase the Albu will change the label from `array(x)` to `array([x])`, which will crash the trainning.
And I also find out that there are no field `gt_labels` in all configs file in mmcls. So I think is inherit from mmdet.
Becuase of that I correct it in mmcls with `gt_label` and added some code to change it back to `array(x)` after albu change it to incorrect type `array([x])`
Thx for @Ezra-Yu ,we can find it in here: 
https://github.com/albumentations-team/albumentations/blob/a8dc46ee29f9573c8569213f0d243254980b02f1/albumentations/core/composition.py#L276-L282
If need to test this PR before mmcls merge into master branch, we need to **reinstall mmcls after modefied this file**.
```shell
pip uninstall mmcls -y …
```
> [Fix Serious BUG] Using Albu will crash the trainning

- mmcls/models/backbones/swin_transformer.py
- tests/test_models/test_backbones/test_swin_transformer.py
The original implementation of Swin-Transformer output after the downsample layers, cause the output cannot to be used in the downstream tasks.
Add an argument `out_after_downsample` and default to set False. If False, output the feature map before the downsample layers.
The default behavior of `SwinTransformer` changed, but the checkpoints are not changed. And you can return the original behavior by setting `out_after_downsample=True`.
```python
>>> import torch
>>> from mmcls.models import build_backbone
>>> inputs = torch.rand(1, 3, 224, 224)
>>>
>>> cfg = dict(type='SwinTransformer', arch='base', out_indices=(0, 1, 2, 3))
>>> model = build_backbone(cfg)
>>> outs = model(inputs)
>>> for out in outs:
...     print(out.shape)
torch.Size([1, 128, 56, 56])
torch.Size([1, 256, 28, 28]) …
```
> [Fix] Fix the output position of Swin-Transformer.

- mmcls/models/classifiers/image.py
- tests/test_models/test_classifiers.py
- tools/analysis_tools/get_flops.py
We should add `forward_dummy` to query flops by mmcv (https://github.com/open-mmlab/mmcv/blob/master/mmcv/cnn/utils/flops_counter.py#L38). Althugh we already have `extract_feat`, but it's not sync with mmdetection(https://github.com/open-mmlab/mmdetection/blob/master/mmdet/models/detectors/single_stage.py#L48). 
we should sync both projects since many people may want to put both together into a single project.
> Dummy forward

- mmcls/core/hook/precise_bn_hook.py
- tests/test_runtime/test_preciseBN_hook.py
Using train_step instead of forward in PreciseBNHook, to avoid error when using preciseBNHook in MLU.
refer to #942 
No
**Before PR**:
**After PR**:
> Using train_step instead of forward in PreciseBNHook

- mmcls/models/utils/attention.py
Since logit_scale in the WindowMSAV2 module is a learnable parameter and it could potentially be on the GPU, while torch instantiates torch.tensor() on the CPU, this results in an error  :
`RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument max in method wrapper_clamp_Tensor)`
Forced to create a tensor on same device. 
Currently SwinV2 is not implemented in downstream repositories?
Minimal example to reproduce the error:
```
import torch
from mmcls.models.backbones import SwinTransformerV2
model = SwinTransformerV2().to('cuda:0')
model(torch.rand((2, 3, 512, 512), device='cuda:0'))
```
**Before PR**:
**After PR**:
> [Fix] Device mismatch in SwinV2

- tools/deployment/pytorch2onnx.py
I'm the author of onnx-simplifier. Recently I published onnxsim v0.4.0. In the latest version, dynamic input shapes are natively supported with no need for extra flags like `dynamic_input_shapes`. `custom_lib` and `input_data` is also not needed.
> Upgrade onnxsim to v0.4.0

- mmcls/models/backbones/t2t_vit.py
- tests/test_models/test_backbones/test_t2t_vit.py
The function `get_sinusoid_encoding` implemented here (https://github.com/open-mmlab/mmclassification/blob/master/mmcls/models/backbones/t2t_vit.py#L216-#L242)  is copied from a third-party implementation (https://github.com/jadore801120/attention-is-all-you-need-pytorch/blob/master/transformer/Models.py#L31), while we did not point this out. I re-write the numpy based implementation with pytorch.
Rewrite the function at `mmcls/models/backbones/t2t_vit.py` and add the unit test at `tests/test_models/test_backbones/test_t2t_vit.py`.
If …
> [Refactor] Re-write get_sinusoid_encoding from third-party implementation

- tools/kfold-cross-valid.py
- tools/test.py
- tools/train.py
In MMCLS 0.x, we enable the `pin_memory` and `persistent_workers` options by default. But in MMCLS 1.x, these options are not enabled in MMEngine by default.
Defaults to enable `persistent_workers`, `pin_memory` and use default collate_fn in the tools, such as `tools/train.py`, `tools/test.py` and `tools/kfold-cross-valid.py`.
No, these options won't affect the options set in config files. And you can use `--no-pin-memory` and `--no-persistent-workers` to disable these behaviors.
> [Imporve] Update tools to enable pin_memory and persistent_workers by default.

- .dev_scripts/benchmark_regression/1-benchmark_valid.py
- .dev_scripts/benchmark_regression/2-benchmark_test.py
- .dev_scripts/benchmark_regression/3-benchmark_train.py
- .dev_scripts/benchmark_regression/bench_train.yml
- .pre-commit-config.yaml
- configs/_base_/schedules/imagenet_bs1024_linearlr_bn_nowd.py
- configs/resnet/resnet50_8xb256-rsb-a1-600e_in1k.py
- mmcls/models/losses/label_smooth_loss.py
- tests/test_models/test_losses.py
Refactor and improve dev scripts
1. Refactor to support MMEngine.
2. Support `--cfg-options` to specify the same options
```shell
python .dev_scripts/benchmark_regression/3-benchmark_train.py mm_model \
--job-name cls-amp --work-dir work_dirs/benchmark_train_amp \
--cfg-options optim_wrapper.type='AmpOptimWrapper' optim_wrapper.loss_scale='dynamic'
```
3. Use `--range` to specify the training benchmark range
```shell
python .dev_scripts/benchmark_regression/3-benchmark_train.py mm_model \
--range quarter
python .dev_scripts/benchmark_regression/3-benchmark_train.py mm_model \
--range "=half-year"
```
4. Fix some training configs.
- Use BCE in rsb-a1 training recipe
- Fix the wrong ShuffleNet training schedule.
> [Improve] Update benchmark scripts

- mmcls/models/utils/attention.py
The original clamp operation is hard to read.
Use `np.log` instead for better compatibilities for all pytorch version
**Before PR**:
**After PR**:
> [Fix] fix attention clamp max params

- mmcls/apis/train.py
Val loader should not drop last by default.
add 'drop_last': False in val_loader_cfg by default.
**Before PR**:
**After PR**:
> [fix] val loader should not drop last by default.

- mmcls/models/backbones/repvgg.py
- mmcls/models/utils/attention.py
- tests/test_models/test_backbones/test_repvgg.py
Add `MTSPPF` block and `add_ppf` param for YOLOX-PAI.
[YOLOX-PAI: An Improved YOLOX, Stronger and Faster than YOLOv6](https://arxiv.org/abs/2208.13040)
[official repo](https://github.com/alibaba/EasyCV/tree/master/configs/detection/yolox)
1. add MTSPPF module and support it in RepVGG backbone;
2. support 'stem_channels' in `arch` and add a 'yolox-pai-small' arch cfg
3. Reduce the number of channels to speed up unit testing
https://github.com/open-mmlab/mmdetection/pull/8778
**Before PR**:
**After PR**:
> [Enhancement] RepVGG for YOLOX-PAI

- requirements/runtime.txt
fix `show_result` error.
`fig.add_subplot() == None` when `matplotlib==3.0.3`, here is my callstack:
```bash
> /home/PJLAB/konghuanjun/GitProjects/mmclassification/mmcls/core/visualization/image.py(68)_initialize_fig_save()
-> ax = fig.add_subplot()
(Pdb) p fig
<Figure size 230.4x172.8 with 0 Axes>
(Pdb) n
> /home/PJLAB/konghuanjun/GitProjects/mmclassification/mmcls/core/visualization/image.py(71)_initialize_fig_save()
-> fig.subplots_adjust(left=0, right=1, bottom=0, top=1)
(Pdb) p ax
None
...
(Pdb) matplotlib.__version__ …
```
> [Fix] Add matplotlib minimum version requriments.

- README.md
- README_zh-CN.md
I follow the doc to [install](https://github.com/open-mmlab/mmclassification/blob/master/README.md#installation) the mmcls, 
and I got the error:
```bash
segment fault
```
I look for which library to cause it then I found is  `import torchvision`. So I look for the answer on the web and I found the answer: **set the version of it**.
Add version for torchvision in the installation of the doc. The version is according to the [Pytorch official website V1.10.0](https://pytorch.org/get-started/previous-versions/#v1100)
**Before PR**:
**After PR**:
> [Docs] Add version for torchvision to avoide error.

- mmcls/apis/test.py
ProgressBar supports multiple updates at once. See https://github.com/open-mmlab/mmcv/blob/1f2500102834a01b86bf9ae4db227cd8d724fa6e/mmcv/utils/progressbar.py#L35
Replace loop
> [Improve] replace loop of progressbar in api/test

- tests/test_models/test_utils/test_attention.py
- tests/test_models/test_utils/test_misc.py
`torch.meshgrid()` has started raising a warning when not called with an explicit indexing parameter:
https://pytorch.org/docs/stable/generated/torch.meshgrid.html
Provide `indexing='ij'` to all calls to `torch.meshgrid` that don't already specify indexing.
**Before PR**:
**After PR**:
> [Fix] Fix warning with `torch.meshgrid`.

- docs/en/user_guides/inference.md
- docs/zh_CN/user_guides/inference.md
- mmcls/apis/inference.py
Get pred_scores from inference api.
```python
from mmcls.apis import inference_model, init_model
from mmcls.utils import register_all_modules
config_path = './configs/resnet/resnet50_8xb32_in1k.py'
checkpoint_path = 'https://download.openmmlab.com/mmclassification/v0/resnet/resnet50_8xb32_in1k_20210831-ea4938fc.pth' # can be a local path
img_path = 'demo/demo.JPEG'   # you can specify your own picture path
register_all_modules()
model = init_model(config_path, checkpoint_path, device="cpu")  # device can be 'cuda:0'
result = inference_model(model, img_path)
```
`result` is a dictionary containing `pred_label`, `pred_score`, `pred_scores` and `pred_class`, the result is as follows:
```text
{"pred_label":65,"pred_score":0.6649366617202759,"pred_class":"sea snake", "pred_scores": [..., …
```
> [Enhancement] Get scores from inference api

- .github/workflows/build.yml
The latest timm only supports PyTorch>=1.7.0, which causes CI fails.
Only do unit tests about timm on a specified PyTorch version,
**Before PR**:
**After PR**:
> [CI] Fix CI error from timm and PyTorch version.

- tools/analysis_tools/analyze_results.py
Update analyze_results.py for mmcls v1.0.
```
mim test mmcls configs/resnet/resnet18_8xb32_in1k.py --checkpoint https://download.openmmlab.com/mmclassification/v0/resnet/resnet18_8xb32_in1k_20210831-fbbb1da6.pth --dump result.pkl
mim run mmcls analyze_results configs/resnet/resnet18_8xb32_in1k.py result.pkl --out-dir show
```
**Before PR**:
**After PR**:
> [Enhancement] Update analyze_results.py for dev-1.x

- mmcls/apis/inference.py
Let MMCLS1.x get classes information from checkpoint during inference instead of using imagenet classes initialization …
> Fix for MMCLS1.x not being able to get classes information in checkpoint during inference

- mmcls/models/backbones/convnext.py
There are flowing warning when use dist_train.sh to train convnext 
> [W reducer.cpp:347] Warning: Grad strides do not match bucket view strides. This may indicate grad was not created according to the gradient layout contract, or that the param's strides changed since DDP was constructed.  This is not an error, but may impair performance.
call contiguous after permute in layernorm, and the performance actually improve 3x in my test 
Does the modification introduce changes that break the backward compatibility of the downstream …
>  fix performance issue in convnext DDP train

- mmcls/apis/train.py
- mmcls/datasets/samplers/distributed_sampler.py
- mmcls/utils/distribution.py
Added ascending device support in mmcv.
- The main modification points are as follows: 
1. In ```mmcls/apis/train.py```, We added an NPU device in the DDP scenario, and the mixing accuracy is enabled by default when using the NPU
2. In ``mmcls/utils/distribution.py```, We have added DP and DDP classes for NPU
3. In ``mmcls/datasets/samplers/distributed_sampler.py```, We added device judgment to make the broadcast within the sync_random_seed function execute correctly on the npu
A new mmcv containing the NPU background needed.
We …
> [Feature] Support mmcls with NPU backend.

- mmcls/models/heads/__init__.py
- mmcls/models/heads/arc_face_head.py
- mmcls/models/heads/arcface_head.py
- tests/test_models/test_heads.py
Support [ArcFace loss](https://arxiv.org/abs/1801.07698).
**Before PR**:
**After PR**:
> Add arcface head

- mmcls/datasets/dataset_wrappers.py
Further detail for the doc for datasets/dataset_wrappers/ClassBalancedDataset. The original doc seems
confusing in some ways.
I just modify the docstring for the datasets/dataset_wrappers/ClassBalancedDataset.
**Before PR**:
**After PR**:
> [doc] further detail for the doc for datasets/dataset_wrappers/ClassBalancedDataset

- docs/en/tools/miscellaneous.md
I found a simple typo while reading docs.
`tools/print_config.py` => `tools/misc/verify_dataset.py`
**Before PR**:
**After PR**:
> [Docs] Fix typo in miscellaneous.md

- mmcls/models/necks/__init__.py
- mmcls/models/necks/reduction.py
- tests/test_models/test_necks.py
In some cases, it is necessary to reduce the dimension of extracted feature, so ``Reduction`` is implemented in necks.
```python
model = dict(
type='ImageClassifier',
backbone=dict(
type='ResNet',
depth=101,
num_stages=4,
out_indices=(3,),
style='pytorch'
),
neck=[
dict(type='GeneralizedMeanPooling'),
dict(type='LinearReduction',
in_channels=2048,
out_channels=512,
act_cfg=dict(type='ReLU'),
norm_cfg=dict(type='BN1d')
)
],
head=dict(
type='LinearClsHead',
num_classes=1000,
in_channels=2304,
loss=dict(type='CrossEntropyLoss', loss_weight=1.0),
topk=(1, 5),
),
)
```
**Before PR**:
**After PR**:
> [Feature] add reduction for neck

- docs/en/_static/js/custom.js
- docs/en/conf.py
- docs/en/stat.py
- docs/zh_CN/_static/js/custom.js
- docs/zh_CN/conf.py
- docs/zh_CN/stat.py
Use the [datatable](https://datatables.net/) package to enable sorting and searching the model summary table in the docs.
> [Docs] Support sort and search the Model Summary table.

- mmcls/models/backbones/swin_transformer_v2.py
As titled.
**Before PR**:
**After PR**:
> [Enhance] add delete params info in logging when load swinv2 checkpoints

- mmcls/apis/train.py
- mmcls/core/utils/dist_utils.py
- mmcls/datasets/samplers/distributed_sampler.py
- mmcls/utils/distribution.py
Support training and distributed-training on MLU device.
Add MLUDataParallel and MLUDistributedDataParallel support to model wrapper.
Modified sync_random_seed with auto_select_device
Only Support MLU training with MMCV>=1.6.0.
It will automatically select device to train model.
Test with ResNet18 on imagenet.
**Before PR**:
**After PR**:
> [Feature]: Support mmclassification with MLU backend

- mmcls/engine/optimizers/__init__.py
- mmcls/engine/optimizers/adan_t.py
Add the new optimizer, [Adan](https://arxiv.org/abs/2208.06677)
Add adan_t.py in `mmclassification/mmcls/engine/optimizers/adan_t.py`
Please see the attached [config&log](https://github.com/open-mmlab/mmclassification/files/10008646/config.log.zip) files for a detailed example.
> [Feature] Add adan optimizer

- mmcls/datasets/cifar.py
- mmcls/datasets/cub.py
- mmcls/datasets/custom.py
- mmcls/datasets/mnist.py
- mmcls/datasets/utils.py
- mmcls/datasets/voc.py
- mmcls/engine/hooks/visualization_hook.py
- tests/test_engine/test_hooks/test_visualization_hook.py
Remove all `FileClient` and use the new API in MMEngine.
> [Refactor] Refactor to use new fileio API in MMEngine.

- docs/en/device/npu.md
- tools/dist_train_arm.sh
update npu results, add MobileNetV2 MobileNetV3 results, add notes, add dist_train_arm.sh
tools/dist_train_arm.sh
docs/en/device/npu.md
> [feature] update npu results, add dist_train_arm.sh

- docs/en/advanced_guides/runtime.md
- docs/en/api/engine.rst
- mmcls/engine/hooks/__init__.py
- mmcls/engine/hooks/ema_hook.py
- tests/test_engine/test_hooks/test_ema_hook.py
Sometimes, we want to get the metrics of both EMA and original models during validation and testing.
Add an `EMAHook` in MMCLS which inherits the `EMAHook` in MMEngine.
Almost not, the only breaking is the modification about `after_load_checkpoint`. In the original logic, both the source model and the ema model load ema parameters if `resume=False`, which caused we cannot to access the source parameters during testing.
In this PR, this logic is moved to `before_train`, which means the `runner.load_or_resume` will always load ema parameters to the ema model and load source parameters to the source model. And only when `runner.train` is called and `resume=False`, we will load ema parameters to the source parameters
```python
custom_hooks = [
dict(
type='EMAHook',
momentum=0.001, …
```
> [Enhance] Support evaluate on both EMA and non-EMA models.

- docs/en/_static/js/custom.js
- docs/en/get_started.md
- docs/zh_CN/_static/js/custom.js
- docs/zh_CN/get_started.md
- requirements/docs.txt
The original tutorial introduced `mim`, `mmengine`, and `mmcv` before installing mmclassification.
But most are unnecessary, and we can compress the entire install procedure into one lines (package mode) 
```bash
pip install openmim && mim install "mmcls>=1.0.0rc0"
```
and three lines (dev mode)
```bash
git clone -b 1.x https://github.com/open-mmlab/mmclassification.git
cd mmclassification
pip install openmim && mim install -e .
``` …
> [Docs] Update install tutorial.

- .gitignore
- projects/README.md
- projects/example_project/README.md
- projects/example_project/configs/examplenet_8xb32_in1k.py
- projects/example_project/models/__init__.py
- projects/example_project/models/example_net.py
In this PR, we introduce a new `projects` folder in MMClassification. The `projects` is used to support some new algorithms and community projects efficiently. In this folder, we won't be strict with code style and other requirements. And some projects can also be moved to the core package after refactoring.
**Before PR**:
**After PR**:
> [Project] Add project instructions and example project.

- .circleci/config.yml
- .github/workflows/build.yml
Update master branch CI.
**Before PR**:
**After PR**:
> [CI] Update CI of the master branch

- mmcls/datasets/transforms/auto_augment.py
Fix import path.
This branch is supposed to be compatible with mmcv 2.x, so I corrected the import path, ref in mmcv: https://github.com/Francis777/mmcv/blob/fb39e1e568c49fcd97f9a56cb70a89d6693738c7/mmcv/transforms/__init__.py#L14
**Before PR**:
**After PR**:
> fix import

- mmcls/apis/inference.py
- mmcls/apis/model.py
- requirements/runtime.txt
The `modelindex` package is missing in the requirements.
- Add it in the `requirements/runtime.txt.`
- In the `mmcls.apis` package, avoid importing some packages and registering mmcls models directly. This modification can speed up `import mmcls` (from ~3.2s to ~0.7s)
**Before PR**:
**After PR**:
> [Fix] Fix the requirements and lazy register mmcls models.

- .dev_scripts/ckpt_tree.py
- .dev_scripts/compare_init.py
- .dev_scripts/generate_readme.py
Add some tools for help development.
1. `ckpt_tree.py`: To print the model structure with only state dict. It's helpful when you need to compare the keys of two state dicts.
For example:
```bash
python .dev_scripts/ckpt_tree.py ckpt/resnet50_8xb32_in1k_20210831-ea4938fc.pth --depth 3
```
output:
2. `compare_init.py`: To compare the weight distribution between two state dicts. It will use the Kolmogorov-Smirnov test to compare the same key between two parameters. It's helpful when you need to align the initialization method with the official implementation.
For example:
```bash
python .dev_scripts/compare_init.py resnet1_init.pth resnet2_init.pth --show
```
4. `generate_readme.py`: To generate a `README.md` from the metafile.
For example:
```bash
python .dev_scripts/generate_readme.py …
```
> [Feature] Add some scripts for development.

- configs/_base_/models/convnext/convnext-base.py
- configs/_base_/models/convnext/convnext-large.py
- configs/_base_/models/convnext/convnext-small.py
- configs/_base_/models/convnext/convnext-tiny.py
- configs/_base_/models/convnext/convnext-xlarge.py
- configs/_base_/schedules/imagenet_bs1024_adamw_swin.py
- configs/convnext/README.md
- configs/convnext/convnext-base_32xb128_in1k.py
- configs/convnext/convnext-base_32xb128_in21k.py
- configs/convnext/convnext-large_64xb64_in1k.py
- configs/convnext/convnext-large_64xb64_in21k.py
- configs/convnext/convnext-small_32xb128_in1k.py
- configs/convnext/convnext-tiny_32xb128_in1k.py
- configs/convnext/convnext-xlarge_64xb64_in1k.py
- configs/convnext/convnext-xlarge_64xb64_in21k.py
- configs/convnext/metafile.yml
- docs/en/migration.md
- docs/en/user_guides/config.md
- mmcls/models/backbones/convnext.py
I have reproduced the accuracy of ConvNeXt's tiny, small and base architectures.
Update all ConvNeXt configs. And since the ConvNeXt-base accuracy is a little lower than the original accuracy (83.66 vs 83.85), I reserved the 3rd party ConvNeXt-base checkpoint.
**Before PR**:
**After PR**:
> [Reproduce] Update ConvNeXt config files.

- mmcls/models/__init__.py
- mmcls/models/tta/__init__.py
- mmcls/models/tta/score_tta.py
- tests/test_models/test_tta.py
- tools/test.py
To support Test-Time-Aug (TTA).
- Add `AverageScoreTTAModel` inherited from the `BaseTTAModel` in MMEngine.
- Add `--tta` option in `tools/test.py` to enable TTA during the test.
**To use the default TTA (average the classification scores of images w/ and w/o flip)**
```bash
python tools/test.py configs/resnet/resnet50_8xb32_in1k.py checkpoints/resnet50_in1k.pth --tta
```
**To use your own custom TTA method**
1. Add `tta_model` and `tta_pipeline` in your config file:
```python
...
tta_model = dict(type='AverageScoreTTAModel')
tta_pipeline = [
dict(type='LoadImageFromFile'),
dict(type='ResizeEdge', scale=384, edge='short'),
dict(type='CenterCrop', crop_size=384),
dict(type='TestTimeAug',
transforms=[
[
dict(type='Resize', scale=224),
dict(type='Resize', scale=384)
],
[ …
```
> [Feature] Support TTA and add `--tta` in `tools/test.py`.

- .circleci/config.yml
- .github/workflows/build.yml
- .owners.yml
- mmcls/core/visualization/image.py
on my m1 mac, when I run example https://github.com/wangruohui/sjtu-openmmlab-tutorial/blob/main/cls-2-train.ipynb
encounter error is that
```
Traceback (most recent call last):
File "cls-1-inference.py", line 72, in <module>
show_result_pyplot(model, 'banana.png', result)
File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/apis/inference.py", line 114, in show_result_pyplot
model.show_result(
File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/models/classifiers/base.py", line 212, in show_result
img = imshow_infos(
File "/Users/zoupeng/miniconda3/envs/openmmlab/lib/python3.8/site-packages/mmcls/core/visualization/image.py", line 333, in imshow_infos
_, img = manager.put_img_infos(
File …
```
> [Fix] adapt to matplotlib fig 1px precision lost

- .dev_scripts/check_metafile.py
- .dev_scripts/fill_metafile.py
- .pre-commit-config.yaml
- configs/swin_transformer_v2/metafile.yml
- configs/swin_transformer_v2/swinv2-base-w12_8xb128_in21k-192px.py
- configs/swin_transformer_v2/swinv2-large-w12_8xb128_in21k-192px.py
- mmcls/apis/model.py
- tests/test_apis/test_model.py
1. Add a metafile fill tool
2. Add a metafile validation tool and add it to the pre-commit hooks.
**The metafile fill tool**
[![asciicast](https://asciinema.org/a/549609.svg)](https://asciinema.org/a/549609)
> [Tool] Add metafile fill and validation tools.

- tools/test.py
Originial code assign the result of `list.append()` to a variable which is None and cause error. 
**Before …
> Fix bug in test tools

- docs/en/api/datasets.rst
- mmcls/datasets/__init__.py
- mmcls/datasets/inshop.py
- tests/test_datasets/test_datasets.py
Support [InShop dataset](https://mmlab.ie.cuhk.edu.hk/projects/DeepFashion/InShopRetrieval.html) .
```
>>> from mmcls.data import InShop
>>> data_root = 'data/inshop'
>>> inshop_train_cfg = dict(data_root='data/inshop', split='train')
>>> inshop_train = InShop(**inshop_train_cfg)
>>> len(inshop_train)
25882
>>> inshop_query_cfg = dict(data_root='data/inshop', split='query')
>>> inshop_query = InShop(**inshop_query_cfg)
>>> len(inshop_query)
14218
>>> inshop_gallery_cfg = dict(data_root='data/inshop', split='gallery')
>>> inshop_gallery = InShop(**inshop_gallery_cfg)
>>> len(inshop_gallery)
12612
```
**Before PR**:
**After PR**:
> [Feature] Support InShop Dataset (Image Retrieval).

- mmcls/models/necks/gem.py
- tests/test_models/test_necks.py
Enable to toggle whether Gem Pooling is trainable or not.
[reference](https://github.com/ChristofHenkel/kaggle-landmark-2021-1st-place/blob/main/models/ch_mdl_hybrid_transformer.py#L197)
```python
class GeneralizedMeanPooling(nn.Module):
...
def __init__(self, p=3., eps=1e-6, clamp=True, p_trainable=True):
...
if p_trainable:
self.p = Parameter(torch.ones(1) * p)
else:
self.p = p
...
```
> [Enhance] Enable to toggle whether Gem Pooling is trainable or not.

- mmcls/engine/hooks/retriever_hooks.py
- mmcls/models/retrievers/image2image.py
- mmcls/utils/progress.py
Fix retriever multi-GPUs bug refer to #1310 
1. handle with DDP-wrapper model
2. remove the return statement in `progress.track_on_main_process`, (since there is yield in the function definition).
**Before PR**:
**After PR**:
> [Fix] Fix retrieval multi gpu bug

- docs/en/migration.md
- docs/en/useful_tools/log_result_analysis.md
- docs/en/useful_tools/print_config.md
- docs/zh_CN/migration.md
- docs/zh_CN/useful_tools/log_result_analysis.md
- docs/zh_CN/useful_tools/print_config.md
- mmcls/utils/__init__.py
- mmcls/utils/analyze.py
- tests/test_utils/test_analyze.py
- tools/analysis_tools/analyze_logs.py
- tools/analysis_tools/analyze_results.py
- tools/analysis_tools/eval_metric.py
- tools/misc/print_config.py
Some analysis tools are not available and documentations are outdated.
Update these analysis tools and documentation.
The interface of the `tools/analysis_tools/eval_metric.py` is changed.
In the new `eval_metric.py`, you don't need to specify the config file, and accordingly, you need to use
`--metric` argument to specify the metrics to calculate. For example:
```shell
python tools/analysis_tools/eval_metric.py results.pkl --metric type=Accuracy topk=1,5
python tools/analysis_tools/eval_metric.py results.pkl --metric type=Accuracy \
--metric type=SingleLabelMetric items=precision,recall,f1-score
```
And the output of `mmcls.utils.load_json_log` changed to the below format to fit the new log format.
```python
{
'train': [
{"lr": 0.1, "time": 0.02, "epoch": 1, "step": 100},
{"lr": 0.1, …
```
> [Refactor] Update analysis tools and documentations.

- .circleci/test.yml
- mmpretrain/models/backbones/twins.py
- mmpretrain/models/utils/attention.py
- tools/test.py
- tools/train.py
Pytorch 2.0 has official `scaled_dot_product_attention` implementation, which will automatically select the
attention implementation like `FlashAttention` and `Memory-Efficient Attention`.
If the PyTorch version is higher than 2.0, use the official `scaled_dot_product_attention` in the
`MultiheadAttention`.
Here is the speed comparsion on test (NVIDIA A100, FP16):
**Original**:
```text
03/23 12:19:48 - mmengine - INFO - Epoch(test) [10/98]    eta: 0:02:17  time: 1.5650  data_time: 0.5420  memory: 4155  
03/23 12:19:52 - mmengine - INFO - Epoch(test) [20/98]    eta: 0:01:14  time: 0.3493  data_time: 0.0018  memory: 4155  
03/23 12:19:55 - mmengine - INFO - Epoch(test) [30/98]    eta: 0:00:51  time: 0.3411  data_time: 0.0014  memory: 4155  
03/23 12:19:58 - mmengine - INFO - Epoch(test) …
```
> [Improve] Use PyTorch official `scaled_dot_product_attention` to accelerate `MultiheadAttention`.

- mmpretrain/models/backbones/vit_sam.py
> [Refactor] Support resizing pos_embed while loading ckpt and format output

- mmpretrain/models/losses/cross_entropy_loss.py
A quick fix to issue #1520.  refer to https://discuss.pytorch.org/t/multi-label-binary-classification-result-type-float-cant-be-cast-to-the-desired-output-type-long/117915
> [Fix] Support bce loss without batch augmentations

- docs/en/user_guides/inference.md
- docs/zh_CN/user_guides/inference.md
- mmpretrain/apis/image_classification.py
as title. not include the ImageRetrievalInferencer
**Before PR**:
**After PR**:
> [DOC] Refine Inference Doc

- mmpretrain/models/heads/multi_task_head.py
in the pull request https://github.com/open-mmlab/mmpretrain/pull/1229 , for the extreme case that we have a full-mask we do for the loss = 0 which will cause problems to calculate the gradient of the loss. here i use the torch vector of the image to create a loss =0
https://github.com/open-mmlab/mmpretrain/issues/1393
the same as https://github.com/open-mmlab/mmpretrain/pull/1426
**Before PR**:
**After PR**:
> [Fix] Fix multi-task-head loss potential bug

- mmpretrain/datasets/__init__.py
- mmpretrain/datasets/scienceqa.py
> [Feature]: Add scienceqa

- configs/riformer/README.md
- mmpretrain/models/backbones/riformer.py
The reproduce code of RIFormer seems to be incorrect when handling stage freeze. This may cause an incorrect result.
Add the correct arxiv website of RIFormer to Readme.
Repair the index in for loop of freeze_stage. Change the default value of freeze_stage to -1.
Add the paper pdf website to its Readme.
I'm uncertain whether this modification will disrupt the standardization of the 'freeze_stage' parameter in the mmpretrain project.
> Incorrect stage freeze on RIFormer Model

- configs/_base_/datasets/nocaps.py
- configs/blip/README.md
- configs/blip/blip-base_8x32_nocaps.py
- mmpretrain/datasets/__init__.py
- mmpretrain/datasets/nocaps.py
- mmpretrain/evaluation/metrics/__init__.py
- mmpretrain/evaluation/metrics/nocaps.py
Support NoCap dataset based on BLIP.
**Before PR**:
**After PR**:
> [Feature] Support NoCap dataset based on BLIP.

- tools/visualization/vis_cam.py
Fix bug of vis_cam when using swin refer to https://github.com/open-mmlab/mmpretrain/issues/1580
set default out_type to avg_featmap
**Before PR**:
**After PR**:
> [FIX] Fix bug of vis_cam when using swin

- configs/_base_/datasets/inshop_bs32_448.py
- configs/arcface/README.md
- configs/arcface/metafile.yml
- docs/en/api/evaluation.rst
- mmpretrain/apis/image_retrieval.py
- mmpretrain/evaluation/metrics/__init__.py
- mmpretrain/evaluation/metrics/retrieval.py
- projects/gradio_demo/launch.py
- tests/test_evaluation/test_metrics/test_retrieval.py
1. Add retrieval mAP and unit tests relate to https://github.com/open-mmlab/mmpretrain/pull/980
**Before PR**:
**After PR**:
> [Feature] Add retrieval mAP

- .pre-commit-config.yaml
- mmcls/models/losses/accuracy.py
ARM chip with low version GCC version may cause calculation errors.
reference: https://github.com/pytorch/pytorch/issues/75411
This leads to incorrect accuracy calculations, even though the model is correctly trained.
When the model is trained on the arm chip, try to calculate the accuracy on cuda/npu to avoid calculation errors caused by sum operations.
Not affected.
We have verified the correctness on some configs, such as resnet18_8xb16_cifar10.py and resnet152_8xb16_cifar10.py
> [Fix] Fix calculation errors on ARM chip

- configs/_base_/datasets/coco_okvqa.py
- configs/blip/README.md
- configs/blip/blip-base_8xb32_okvqa.py
Support `OK-VQA` dataset.
Reuse the dataset file of `COCOVQA`, only need to change the annotation file, so **only need to change the config**.
You can easily download `OK-VQA` annotation file at https://okvqa.allenai.org/download.html
Or you can fetch it from /mnt/petrelfs/share_data/wangyiqin/coco/annotations/
A example config for BLIP zero-shot inference is provided. It perform an ACC of 40.6.
Example command:
```bash
sh tools/slurm_test.sh <patrition> <jobname> configs/blip/blip-base_8xb32_okvqa.py /mnt/petrelfs/share_data/wangyiqin/blip_ckpt/blip-base_3rdparty-capflit_vqa_20230505-81488941.pth
```
> [Feature] Support OK-VQA dataset

- mmpretrain/datasets/imagenet.py
if there is 'meta/train.txt' in the imagenet dataset folder.
the ann_file would be `data_root/data_root/meta/train.txt`
**Before PR**:
**After PR**:
> [FIX] Fix bug loading IN1k dataset

- MANIFEST.in
- dataset-index.yml
- docs/en/user_guides/dataset_prepare.md
- docs/zh_CN/user_guides/dataset_prepare.md
- setup.py
- tools/dataset_converters/odl_cub_preprocess.sh
- tools/dataset_converters/odl_imagenet1k_preprocess.sh
Download dataset by using MIM&OpenDataLab
relay to https://github.com/open-mmlab/mim/pull/212
```Bash
pip install -U opendatalab
odl login
mim download mmpretrain --dataset imagenet1k
mim download mmpretrain --dataset cub
```
**Before PR**:
**After PR**:
> [Feat] Download dataset by using MIM&OpenDataLab

- mmpretrain/models/backbones/vision_transformer.py
Fix the bug in https://github.com/open-mmlab/mmpretrain/pull/1656
With the implementation in https://github.com/open-mmlab/mmpretrain/pull/1656, `ckpt_pos_embed_shape` will be converted to a tuple, and will cause a bug in the judgment of whether to remove the cls token:
```python
if (not self.with_cls_token and ckpt_pos_embed_shape[1] == self.pos_embed.shape[1] + 1):
...
```
In this PR, the removal of the cls token is moved ahead of the process of resizing `pos_embed`. This implementation has undergone accuracy verification. …
> [Refactor] refactor `_prepare_pos_embed` in ViT to fix bug in loading old checkpoint

- docs/en/migration.md
- docs/zh_CN/migration.md
`RandomFlip` argument rename from `flip_prob` to `flip`, fix to `prob`
**Before PR**:
**After PR**:
> [DOC] Fix typo in docs/*/migration.md

- docs/zh_CN/advanced_guides/modules.md
The English version of the document differs from the Chinese content, and it appears that the Chinese version contains typos caused by using Pinyin.
"涵盖了模型直接绝大多数的差异" -> "涵盖了模型之间绝大多数的差异"
English edition:
"backbone: usually a feature extraction network that records the major differences between models, e.g., ResNet, MobileNet."
**Before PR**:
**After PR**:
> [Docs] fix doc typos

- mmpretrain/models/backbones/vision_transformer.py
An error is raised when calling the method _freeze_stages of VisionTransformer without cls_token. However, we should be able to freeze some layers if the model doesn't contain any cls_token.
In the method _freeze_stages of VisionTransformer, freeze the cls_token only if it is not None.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …
> [Fix] Freezing of cls_token in VisionTransformer

- mmpretrain/datasets/transforms/auto_augment.py
- tests/test_datasets/test_transforms/test_auto_augment.py
Fix the issue #1711 . 
`Image.filter()` is not an in-place operation, its output must be assigned to a variable. In the original code, the output (blurred image) is not assigned to any variable. 
This PR fix the bug, the output is now assigned to the proper variable.  …
> [Fix] Fix the issue #1711 "GaussianBlur doesn't work"

- tests/test_engine/test_hooks/test_densecl_hook.py
- tests/test_engine/test_hooks/test_ema_hook.py
- tests/test_engine/test_hooks/test_simsiam_hook.py
- tests/test_engine/test_hooks/test_swav_hook.py
- tests/test_engine/test_hooks/test_switch_recipe_hook.py
The current test case is only compatible with cpu and cuda devices, and an error will be reported when testing on the Ascend NPU.  
`AssertionError: The values for attribute 'device' do not match: npu:0 != cpu.`
Replace the original 'torch.cuda.is_available()' function with the 'get_device' function.
Does not affect.
We have passed all 637 test cases of mmpretrain on Ascend npu.
**Before PR**:
- [√] Pre-commit or other linting tools are used to fix the potential lint issues.
- [√] Bug fixes are fully covered by unit tests, the case that causes the bug should be added in the unit tests.
- [√] The modification is covered by complete unit tests. If not, please add more unit test to ensure the correctness.
- [√] The documentation has been modified accordingly, like docstring or example …
> [Enhance] Adapt test cases on Ascend NPU.

- configs/blip2/blip2-opt2.7b_8xb32_caption.py
- mmpretrain/models/backbones/beit.py
- mmpretrain/models/multimodal/blip2/Qformer.py
- mmpretrain/models/multimodal/blip2/blip2_caption.py
There is no `loss` function for `BLIP2`.
1. Add the `loss`function of `BLIP2` based on https://github.com/salesforce/LAVIS/blob/main/lavis/models/blip2_models/blip2_opt.py
2. Fix `init_weights` bug of `Qformer`
Using LoRA, the training result on `COCOCaption` datatset is `BLEU@4`: 42.65, `CIDEr`: 143.84
The result reported in the original paper [BLIP-2: Bootstrapping Language-Image Pre-training with Frozen Image Encoders and Large Language Models](https://arxiv.org/pdf/2301.12597.pdf) is `BLEU@4`: 43.7, `CIDEr`: 145.8
However, I …
> [Enhancement] Support training of BLIP2

- mmpretrain/configs/_base_/datasets/imagenet_bs256_beitv2.py
- mmpretrain/configs/_base_/datasets/imagenet_bs64_swin_224.py
- mmpretrain/configs/beit/benchmarks/beit-base-p16_8xb128-coslr-100e_in1k.py
- mmpretrain/configs/beit/benchmarks/beit-base-p16_8xb64_in1k.py
- mmpretrain/configs/beitv2/beitv2_beit-base-p16_8xb256-amp-coslr-1600e_in1k.py
- mmpretrain/configs/beitv2/beitv2_beit-base-p16_8xb256-amp-coslr-300e_in1k.py
- mmpretrain/configs/beitv2/benchmarks/beit-base-p16_8xb128-coslr-100e_in1k.py
- mmpretrain/configs/beitv2/benchmarks/beit-base-p16_8xb64_in1k.py
Adapting New Version of config Adapting BeitV2 Algorithm, based on https://github.com/open-mmlab/OpenMMLabCamp/discussions/335
MMEngine has introduced a novel configuration mechanism, utilizing which we will perform configuration file adaptation.
Add 2 config python files in mmpretrain/configs/_base_/datasets
Add 2 config python files in mmpretrain/configs/beit/
Add 4 config python files in mmpretrain/configs/beitv2
**Before PR**:
**After PR**:
> [CodeCamp2023-335]New version of config adapting BeitV2 Algorithm

- mmpretrain/configs/_base_/datasets/imagenet21k_bs128.py
- mmpretrain/configs/convnext/convnext-base_32xb128_in1k.py
- mmpretrain/configs/convnext/convnext-base_32xb128_in21k.py
- mmpretrain/configs/convnext/convnext-large_64xb64_in1k-384px.py
- mmpretrain/configs/convnext/convnext-large_64xb64_in1k.py
- mmpretrain/configs/convnext/convnext-large_64xb64_in21k.py
- mmpretrain/configs/convnext/convnext-small_32xb128_in1k-384px.py
- mmpretrain/configs/convnext/convnext-small_32xb128_in1k.py
- mmpretrain/configs/convnext/convnext-tiny_32xb128_in1k-384px.py
- mmpretrain/configs/convnext/convnext-tiny_32xb128_in1k.py
- mmpretrain/configs/convnext/convnext-xlarge_64xb64_in1k-384px.py
- mmpretrain/configs/convnext/convnext-xlarge_64xb64_in1k.py
- mmpretrain/configs/convnext/convnext-xlarge_64xb64_in21k.py
- mmpretrain/configs/convnext/convnext_base_32xb128_in1k_384px.py
Adapting New Version of config Adapting  ConvNeXt Algorithm, based on open-mmlab/OpenMMLabCamp#337
MMEngine has introduced a novel configuration mechanism, utilizing which we will perform configuration file adaptation.
Add 1 config python files in mmpretrain/configs/base/datasets
update 1 config python files in mmpretrain/configs/convnext/
Add 12 config python files in mmpretrain/configs/convnext/
**Before PR**:
**After PR**:
> [CodeCamp2023-337] New Version of config Adapting ConvNeXt Algorithm

- dataset-index.yml
- docs/en/user_guides/dataset_prepare.md
- docs/zh_CN/user_guides/dataset_prepare.md
Update datset  download score
refer to https://github.com/open-mmlab/mmaction2/pull/2635
**Before PR**:
**After PR**:
> [DOC] Update datset  download score from opendatalab to openXlab

- projects/dino/README.md
- projects/dino/config/dino_vit-base-p16_8xb64-amp-coslr-100e_in1k.py
- projects/dino/dataset/__init__.py
- projects/dino/dataset/transform/__init__.py
- projects/dino/dataset/transform/processing.py
- projects/dino/engine/__init__.py
- projects/dino/engine/hooks/__init__.py
- projects/dino/engine/hooks/dino_teacher_temp_warmup_hook.py
- projects/dino/models/__init__.py
- projects/dino/models/algorithm/__init__.py
- projects/dino/models/algorithm/dino.py
- projects/dino/models/head/__init__.py
- projects/dino/models/head/dino_head.py
- projects/dino/models/neck/__init__.py
- projects/dino/models/neck/dino_neck.py
- projects/dino/tools/dist_train.sh
- projects/dino/tools/slurm_train.sh
- projects/dino/tools/train.py
Support DINO self-supervised learning in project, based on [https://github.com/open-mmlab/OpenMMLabCamp/discussions/584](https://github.com/open-mmlab/OpenMMLabCamp/discussions/584)
To support DINO in MMpretrain, migrate DINO from MMSelSup.
Add DINO python files in mmpretrain/project
**Before PR**:
**After PR**:
> [CodeCamp2023-584]Support DINO self-supervised learning in project

- mmpretrain/models/heads/mae_head.py
- mmpretrain/models/selfsup/itpn.py
The iTPN implementation does not support for Non-three channel image, while its neck is ready for it.
But I'm not sure if this change is in line with the original design.
Class iTPNHiViT: Pass other argments including channel arg to its superclass(HiViT).
Class MAEPretrainHead: Modify channels from 3 to self.in_channels, which allows users to specify specific channels number.
backbone=dict(type='iTPNHiViT', in_chans=1,),
neck=dict(type='iTPNPretrainDecoder', in_chans=1,),
head=dict(type='MAEPretrainHead', in_channels=1,),
> Add iTPN Supports for Non-three channel image

- configs/llava/README.md
- configs/llava/llava-7b-v1.5_caption.py
- configs/llava/llava-7b-v1.5_vqa.py
- configs/llava/llava-7b-v1_caption.py
- configs/llava/metafile.yml
- mmpretrain/models/multimodal/llava/llava.py
- mmpretrain/models/multimodal/llava/modules.py
- tools/model_converters/llava-delta2mmpre.py
Support LLaVA 1.5 and provide caption and VQA config file.
> [Feature] Support LLaVA 1.5
